Canner/WrenAI

- .github/workflows/ui-lint.yaml
- .github/workflows/ui-test.yaml
Duplicate test & lint workflow was triggered when PR labeled
> Chore(wren-ui): prevent duplicated workflow triggered

- wren-ui/src/apollo/server/repositories/threadRepository.ts
- wren-ui/src/apollo/server/resolvers/askingResolver.ts
- wren-ui/src/apollo/server/services/askingService.ts
In the home page, the listed thread in the side bar should be in create time desc order
> Fix(wren-ui): list threads should in time desc order

- wren-ui/src/apollo/server/adaptors/wrenEngineAdaptor.ts
- wren-ui/src/apollo/server/resolvers/diagramResolver.ts
- wren-ui/src/apollo/server/resolvers/modelResolver.ts
- wren-ui/src/apollo/server/schema.ts
- wren-ui/src/apollo/server/types/diagram.ts
* Add `columns` in view properties
* Add `fields` to view field in diagram API
When querying
```graphql
query Diagram {
diagram {
views {
displayName
id
nodeType
referenceName
statement
viewId
fields {
displayName
id
nodeType
referenceName
type
}
}
}
}
```
You'll get following response for `views`
```js
// ...
views: [
{
"displayName": "view_3",
"id": "c80d524c-a0a7-4d0a-a118-a6e63e0b41c8",
"nodeType": "VIEW",
"referenceName": "view_3",
"statement": "-- Selecting specific columns from the customer table\nSELECT\n  c_custkey,\n  c_name,\n  c_address,\n  c_phone,\n  c_acctbal,\n  c_mktsegment,\n  c_comment\nFROM\n  customer",
"viewId": 4,
"fields": [
{
"displayName": "c_custkey",
"id": "dae76223-d5a2-4898-95a8-c06bbbf3b550",
"nodeType": "FIELD",
"referenceName": "c_custkey",
"type": "int8" …
```
> feat(wren-ui/api): save columns when creating view

- wren-ui/src/apollo/server/mdl/mdlBuilder.ts
- wren-ui/src/apollo/server/mdl/type.ts
Fix engine throws 400 error if properties contains non-string value
> fix(wren-ui/api): fix engine throws 400 error if properties contains non-string value

- wren-ui/src/apollo/client/graphql/__types__.ts
- wren-ui/src/apollo/client/graphql/diagram.generated.ts
- wren-ui/src/apollo/client/graphql/diagram.ts
- wren-ui/src/apollo/client/graphql/view.generated.ts
- wren-ui/src/apollo/client/graphql/view.ts
- wren-ui/src/components/modals/SaveAsViewModal.tsx
- wren-ui/src/components/pages/home/promptThread/AnswerResult.tsx
- wren-ui/src/components/pages/home/promptThread/index.tsx
- wren-ui/src/pages/home/[id].tsx
- wren-ui/src/pages/modeling.tsx
- wren-ui/src/utils/error/dictionary.ts
- wren-ui/src/utils/errorHandler.tsx
- Show view on modeling page
- Save as View Modal
- validate name
- save view
- diagram API
> feat(wren-ui) Support save as View

- wren-ui/src/apollo/client/graphql/__types__.ts
- wren-ui/src/apollo/client/graphql/deploy.generated.ts
- wren-ui/src/apollo/client/graphql/deploy.ts
- wren-ui/src/apollo/server/schema.ts
- wren-ui/src/components/Deploy.tsx
- wren-ui/src/components/HeaderBar.tsx
- wren-ui/src/components/deploy/Context.ts
- wren-ui/src/components/deploy/Deploy.tsx
- wren-ui/src/pages/modeling.tsx
- wren-ui/src/styles/components/button.less
- `Deploy` Button
- Status: `Undeployed changes`, `Deploying`, `synced`
- Connect API
> feat(wren-ui): Support deploy with show status on modeling page 

- wren-ui/src/apollo/client/graphql/view.generated.ts
- wren-ui/src/apollo/client/graphql/view.ts
- wren-ui/src/apollo/server/resolvers/modelResolver.ts
- wren-ui/src/components/diagram/customNode/ModelNode.tsx
- wren-ui/src/components/diagram/customNode/ViewNode.tsx
- wren-ui/src/components/diagram/customNode/utils.tsx
- wren-ui/src/components/pages/modeling/metadata/ViewMetadata.tsx
- wren-ui/src/components/sidebar/modeling/ModelTree.tsx
- wren-ui/src/components/sidebar/modeling/ViewTree.tsx
- wren-ui/src/pages/modeling.tsx
- wren-ui/src/utils/data/type/modeling.ts
- wren-ui/src/utils/diagram/transformer.ts
- Integrating delete to view diagram
- View Metadata drawer
- Connect Diagram API to show view metadata data
- Connect preview view data API to preview view data
- Note: For save as view and delete view (supported by the product at this stage), users need to return to the modeling page and click the Deploy button to trigger the Deploy button
- deleteViewAPI
- diagram API
- previewViewData API
> feat(wren-ui): UI integration API of View for the modeling page

- wren-ui/src/apollo/client/graphql/__types__.ts
- wren-ui/src/apollo/client/graphql/deploy.generated.ts
- wren-ui/src/apollo/client/graphql/deploy.ts
- wren-ui/src/components/HeaderBar.tsx
- wren-ui/src/components/SharePopover.tsx
- Support share connection info
-  Add share info description message
-  Connection information (with a copy button on every property)
> feat(wren-ui): Support share connection info

- wren-ui/src/apollo/server/connectors/duckdbConnector.ts
clear prior session props setting before running init sql.
> Fix(wren-ui): fix invalid session props cause saveDataSource action to fail

- wren-ui/src/apollo/server/factories/pgStrategy.ts
The onboarding saves PG data source that won't return errors because of missing await the promise of connection testing
> fix(wren-ui): Fix pg save data source missing await

- wren-ui/src/components/pages/modeling/metadata/ModelMetadata.tsx
- wren-ui/src/components/table/BaseTable.tsx
- wren-ui/src/components/table/FieldTable.tsx
- wren-ui/src/components/table/RelationTable.tsx
- wren-ui/src/styles/components/table.less
- wren-ui/src/utils/data/type/modeling.ts
- Show metadata in metadata drawer
- Provide expandable table for full description showing
> feat(wren-ui): Show metadata of model & provide expandable rows to table

- wren-ui/src/apollo/client/graphql/__types__.ts
- wren-ui/src/apollo/client/graphql/home.generated.ts
- wren-ui/src/apollo/client/graphql/home.ts
- wren-ui/src/components/pages/home/promptThread/AnswerResult.tsx
- wren-ui/src/components/pages/home/promptThread/StepContent.tsx
- wren-ui/src/components/pages/home/promptThread/index.tsx
- wren-ui/src/components/sidebar/Home.tsx
- Improve thread response UX
- Click a question block to expand or cancel expand it.
- Default open preview data for the last step of the last thread.
> feat(wren-ui): Improve thread response UI

- docker/docker-compose-dev.yaml
- wren-ai-service/demo/Makefile
from now on, ui and wren-ai-service demo app use the same wren-ai-service and qdrant for local development
- expose qdrant ports in docker/docker-compose-dev.yaml
- remove run-qdrant and stop-qdrant in wren-ai-service/demo/Makefile
- rewrite make ui command in wren-ai-service/demo/Makefile
> refine demo site for easier debugging

- wren-ui/src/components/ActionButton.tsx
- wren-ui/src/components/diagram/Context.ts
- wren-ui/src/components/diagram/CustomDropdown.tsx
- wren-ui/src/components/diagram/customNode/Column.tsx
- wren-ui/src/components/diagram/customNode/ModelNode.tsx
- wren-ui/src/components/diagram/customNode/ViewNode.tsx
- wren-ui/src/components/diagram/customNode/utils.tsx
- wren-ui/src/components/diagram/index.tsx
- wren-ui/src/components/modals/DeleteModal.tsx
- wren-ui/src/components/pages/modeling/metadata/ModelMetadata.tsx
- wren-ui/src/components/sidebar/Modeling.tsx
- wren-ui/src/components/sidebar/modeling/ModelTree.tsx
- wren-ui/src/components/sidebar/modeling/ViewTree.tsx
- wren-ui/src/pages/modeling.tsx
- wren-ui/src/utils/enum/modeling.ts
- Add more action in diagram
- Sidebar can only create model, others actions will be added in diagram.
> feat(wren-ui): Add model CRUD UI to diagram

- wren-ai-service/demo/sample_dataset/music_duckdb_mdl.json
- wren-ai-service/demo/sample_dataset/nba_duckdb_mdl.json
This PR is designed to add views to the sample datasets (music, NBA) and includes running the following query to validate that the MDL view integration functions as expected.
- E-commerce
- **What is the average number of items purchased in each state?**
- **Which state has the highest total number of items purchased?**
- **Can you list the total items purchased by customers state-wise?**
- **How does the item purchase volume vary from state to state?**
- **Which states have purchased fewer than 100 items in total?**
- **What are the top three states in terms of total items purchased?**
- **How many items were purchased in total by customers in California?**
- **Compare the number of items purchased between Texas and New York.**
- **What is the lowest number of items purchased in any …
> feature(wren-ai-service): add mdl view in sample dataset for validation

- wren-ui/src/apollo/server/resolvers/diagramResolver.ts
- wren-ui/src/utils/diagram/transformer.ts
A column may have multiple relationships with different models, so it should use `map` to retrieve all relations of the column
In the image below, 
the `orders` model and `payments` model have a relationship but it couldn't be rendered correctly
The `orders.OrderId` only renders one relationship (`orders.OrderId = order_items.OrderId`)
But it actually has multiple relationships with different models:
- `orders.OrderId = order_items.OrderId `
- `payments.OrderId = orders.OrderId`
- `orders.OrderId = reviews.OrderId`
Renders all relationships of `orders.OrderId`
> fix(wren-ui): Column may have multiple relationships with different models

- wren-ui/src/apollo/client/graphql/__types__.ts
- wren-ui/src/components/pages/modeling/ModelDrawer.tsx
- wren-ui/src/components/pages/modeling/form/ModelForm.tsx
- wren-ui/src/pages/modeling.tsx
- wren-ui/src/utils/errorHandler.tsx
UI integrating API to model CRUD
> feat(wren-ui): UI integrating API to model CRUD

- wren-ui/src/apollo/server/data/sample.ts
- wren-ui/src/apollo/server/resolvers/projectResolver.ts
- wren-ui/src/apollo/server/services/modelService.ts
> Chore(wren-ui): add pk to demo dataset

- wren-ui/src/apollo/client/graphql/__types__.ts
- wren-ui/src/apollo/client/graphql/diagram.generated.ts
- wren-ui/src/apollo/client/graphql/diagram.ts
- wren-ui/src/apollo/client/graphql/relationship.generated.ts
- wren-ui/src/apollo/client/graphql/relationship.ts
- wren-ui/src/apollo/server/resolvers/diagramResolver.ts
- wren-ui/src/apollo/server/resolvers/modelResolver.ts
- wren-ui/src/apollo/server/schema.ts
- wren-ui/src/apollo/server/types/diagram.ts
- wren-ui/src/components/modals/RelationModal.tsx
- wren-ui/src/hooks/useCombineFieldOptions.tsx
- wren-ui/src/hooks/useRelationshipModal.tsx
- wren-ui/src/pages/modeling.tsx
- wren-ui/src/utils/errorHandler.tsx
- Integrate UI and CRUD API for relationship
Note: Currently using **reference name**.
> feat(wren-ui): Integrate UI and CRUD API for relationship

- wren-ui/src/components/diagram/customNode/Column.tsx
- wren-ui/src/utils/diagram/transformer.ts
The modeling page could not render after the user saved multiple views
The diagram couldn't find view data to calculate the node with the most column height
- Replenish views data for calculation
- Add calculated field columns height calculation
- Rearrange all column height config
> fix(wren-ui): Fix diagram node height calculation

- wren-ui/src/apollo/server/services/modelService.ts
Fix the "fail to create relation" error when clicking "finish" button with no relation created in the onboarding process.
> Fix(wren-ui): allow sending a empty relation data list

- wren-ui/src/components/pages/home/promptThread/CollapseContent.tsx
- wren-ui/src/hooks/useSetupRelations.tsx
- Fix
- show the connected data source when on the original SQL mode only
- redirect to the home page if there is no relationship data needs to be saved
> fix(wren-ui): show the connected data source when on the original SQL mode only

- wren-ui/src/utils/columnType.tsx
- wren-ui/src/utils/enum/columnType.ts
- wren-ui/src/utils/icons.ts
- wren-ui/src/utils/validator/calculatedFieldValidator.ts
- align column types
- update id, binary icon 
- update calculated field functions type checking
> fix(wren-ui): Align column types with backend connectors provided types

- wren-ui/src/utils/diagram/transformer.ts
> chore(wren-ui): Downgrade columns limit to 10 in diagram

- wren-ui/src/apollo/server/adaptors/wrenAIAdaptor.ts
- wren-ui/src/apollo/server/utils/error.ts
- wren-ui/src/utils/errorHandler.tsx
Handle network error issue for https://github.com/Canner/WrenAI/issues/175
closes #175
- Based on the reference background context, considering the **OTHERS** error code does not directly mean network error, I think we can pass an error message from the AI service to the web and show it on the UI at this stage.
- When there is no network, after the web backend sends the API request to the AI ​​Service, the final return data will be:
```json
{
"status": "failed",
"response": null,
"error": {
"code": "OTHERS",
"message": "Connection error."
}
}
```
- Snippet code for AI Service
We can see the below snippet code of handle exception error:
https://github.com/Canner/WrenAI/blob/d24cdc1090fc9bdaa8722a720b02b1b2281b9786/wren-ai-service/src/web/v1/services/ask_details.py#L106-L113 …
> fix(wren-ui): handle network error issues for asking a question

- wren-ui/src/apollo/server/models/model.ts
- wren-ui/src/apollo/server/resolvers/modelResolver.ts
- wren-ui/src/apollo/server/services/modelService.ts
- wren-ui/src/apollo/server/utils/regex.ts
- wren-ui/src/apollo/server/utils/tests/regex.test.ts
Adjust logic:
- use input displayName to generate referenceName
- validation target is input displayName
created view 
created calculated field
> Feature(wren-ui): adjust display name validation logic of Calculated field & View 

- wren-ui/src/apollo/server/adaptors/wrenEngineAdaptor.ts
- wren-ui/src/apollo/server/resolvers.ts
- wren-ui/src/apollo/server/resolvers/modelResolver.ts
- wren-ui/src/apollo/server/schema.ts
```graphql
mutation PreviewModelData($where: WhereIdInput!) {
previewModelData(where: $where)
}
```
```json
{
"where": {
"id": int
}
}
```
> Feature(wren-ui): Implement Preview model data

- wren-ui/src/apollo/client/graphql/__types__.ts
- wren-ui/src/apollo/client/graphql/diagram.generated.ts
- wren-ui/src/apollo/client/graphql/diagram.ts
- wren-ui/src/apollo/client/graphql/metadata.generated.ts
- wren-ui/src/apollo/client/graphql/metadata.ts
- wren-ui/src/apollo/server/adaptors/wrenAIAdaptor.ts
- wren-ui/src/apollo/server/models/model.ts
- wren-ui/src/apollo/server/resolvers.ts
- wren-ui/src/apollo/server/resolvers/diagramResolver.ts
- wren-ui/src/apollo/server/resolvers/modelResolver.ts
- wren-ui/src/apollo/server/schema.ts
- wren-ui/src/apollo/server/types/diagram.ts
- wren-ui/src/components/EditableWrapper.tsx
- wren-ui/src/components/modals/SaveAsViewModal.tsx
- wren-ui/src/components/pages/modeling/EditMetadataModal.tsx
- wren-ui/src/components/pages/modeling/MetadataDrawer.tsx
- wren-ui/src/components/pages/modeling/metadata/EditBasicMetadata.tsx
- wren-ui/src/components/pages/modeling/metadata/EditModelMetadata.tsx
- wren-ui/src/components/pages/modeling/metadata/EditViewMetadata.tsx
- wren-ui/src/components/pages/modeling/metadata/ViewMetadata.tsx
- wren-ui/src/pages/modeling.tsx
- wren-ui/src/utils/errorHandler.tsx
- wren-ui/src/utils/validator/index.ts
- wren-ui/src/utils/validator/viewValidator.ts
- Support edit view metadata mode
- display name as drawer title (model & view)
- show view’s display name on the **Name** field
- show view’s description
- list all columns
- column name - **Name**
- column type - **Type**
- column description - **Description**
- view (alias) name
- view description
- column description
- update `diagram` API
- add `updateViewMetadata` API
> feat(wren-ui): Support edit view metadata mode

- wren-ui/src/pages/_app.tsx
- wren-ui/src/pages/api/config.ts
- wren-ui/src/utils/env.ts
By design, Nextjs client side cannot receive runtime env, the `NEXT_PUBLIC` env will be converted to frozen value, so we need to provide env at the build time.
> If you build and deploy a single Docker image to multiple environments, all NEXT_PUBLIC_ variables will be frozen with the value evaluated at build time, so these values need to be set appropriately when the project is built.
As an alternative, add an API to retrieve the user option from the backend such as telemetry enabling
> fix(wren-ui): Fix Posthog related env in client

- wren-ui/src/apollo/client/graphql/__types__.ts
- wren-ui/src/apollo/client/graphql/settings.generated.ts
- wren-ui/src/apollo/client/graphql/settings.ts
- wren-ui/src/apollo/server/config.ts
- wren-ui/src/apollo/server/resolvers/projectResolver.ts
- wren-ui/src/apollo/server/schema.ts
- wren-ui/src/components/settings/index.tsx
- wren-ui/src/components/sidebar/index.tsx
- wren-ui/src/utils/icons.ts
- add Wren version number at the settings page bottom left side
- add GitHub link in sidebar 
Need help to export env `WREN_PRODUCT_VERSION` at runtime, cc @wwwy3y3
> feat(wren-ui): Add version number in settings page & Github link

- wren-ui/src/apollo/server/connectors/postgresConnector.ts
- wren-ui/src/apollo/server/factories/postgresStrategy.ts
- wren-ui/src/apollo/server/repositories/projectRepository.ts
- wren-ui/src/apollo/server/resolvers/projectResolver.ts
- wren-ui/src/apollo/server/types/dataSource.ts
- wren-ui/src/components/pages/setup/dataSources/PostgreSQLProperties.tsx
- wren-ui/src/components/settings/DataSourceSettings.tsx
- wren-ui/src/hooks/useSetupConnection.tsx
- Provide SSL property to PostgreSQL data source
- Replenish the Alert component in the update data source settings
close #180
> feat(wren-ui): Support SSL property to Postgres connector

- wren-ui/src/components/pages/modeling/metadata/ModelMetadata.tsx
The model preview data should show the alias as column name.
> chore(wren-ui): Replace model preview data column name to alias

- wren-ui/src/apollo/server/factories/bqStrategy.ts
- wren-ui/src/apollo/server/factories/duckdbStrategy.ts
- wren-ui/src/apollo/server/factories/postgresStrategy.ts
- wren-ui/src/apollo/server/factories/util.ts
- wren-ui/src/apollo/server/mdl/mdlBuilder.ts
- Add a converted function to replace the original name which does not follow the reference name rule.
- Passing the original column name in MDL's  column expression property to WrenEngine
For example:
```Json
{
"name": "_3pointplay",
"expression": "\"3pointplay\""
}
```
close #179
> feat(wren-ui): Convert column original name by following the reference name rule

- wren-ui/src/apollo/server/factories/bqStrategy.ts
- wren-ui/src/apollo/server/factories/postgresStrategy.ts
- wren-ui/src/apollo/server/services/modelService.ts
- wren-ui/src/components/pages/setup/DefineRelations.tsx
fix auto-generated relationships
- Will not see the duplicate rowKey error message in the console.log
- Successfully apply auto-generated table relationships
closes #193
> fix(wren-ui): fix auto-generated relationships

- wren-ui/src/apollo/server/resolvers/modelResolver.ts
- Fix update model metadata failed bug
- Reported issue from: https://discord.com/channels/1227143286951514152/1240988826772570182
The original `model.properties` value is `null`, so putting the value into `JSON.parse()` will get `null`.
**properties** is null not an object, so cannot assign a description to it.
Step 1: onboarding
Step 2: update model description
```js
{
id: 96,
projectId: 4,
displayName: 'public.film',
sourceTableName: 'public.film',
referenceName: 'public_film',
refSql: 'select * from "public"."film"',
cached: 0,
refreshTime: null,
properties: null,
createdAt: '2024-05-17 09:31:43',
updatedAt: '2024-05-17 09:31:43'
}
```
> fix(wren-ui/api): fix update model metadata

- wren-ui/src/apollo/server/repositories/relationshipRepository.ts
- wren-ui/src/apollo/server/services/modelService.ts
- wren-ui/src/components/modals/RelationModal.tsx
- wren-ui/src/components/selectors/CombineFieldSelector.tsx
- wren-ui/src/utils/error/dictionary.ts
- wren-ui/src/utils/validator/index.ts
- wren-ui/src/utils/validator/relationshipValidator.ts
Based on the [issue #193](https://github.com/Canner/WrenAI/issues/193), Considering that there will be multiple relationships between two models in most usage scenarios, we decided to allow multiple relationships at this stage.
- Rules that do not allow the creation of new relationships:
- Same as from and to of existing relationship
- Reverse of from and to of existing relationship
> feat(wren-ui): Update relationship rule

- wren-ui/src/hooks/useAnswerStepContent.tsx
add loading props for the preview data button
> feat(wren-ui): add loading props for preview data button

- wren-ui/src/apollo/server/resolvers/projectResolver.ts
- wren-ui/src/components/diagram/customNode/ModelNode.tsx
- wren-ui/src/utils/diagram/transformer.ts
Self-Referential Relationship: In a self-referential relationship, a column within a model refers back to the same model. For example, consider an `Employee` model where the `reportsTo` column holds the `ID` of another `Employee`, indicating who each employee reports to. This means that the `Employee` model is linked to itself through the `reportsTo` column. 
**Currently, WrenAI does not support creating such relationships where a column in a model references the same model**. 
- Exclude self-referential relationship in auto-generated relationship
- Skip the edge in modeling diagram if model not existed
> fix(wren-ui): Exclude self-referential relationship in auto-generated relationship

- wren-ui/src/apollo/client/graphql/__types__.ts
- wren-ui/src/apollo/client/graphql/home.generated.ts
- wren-ui/src/apollo/client/graphql/home.ts
- wren-ui/src/components/EllipsisWrapper.tsx
- wren-ui/src/components/pages/home/prompt/Result.tsx
- wren-ui/src/components/pages/home/prompt/index.tsx
- wren-ui/src/components/pages/home/promptThread/AnswerResult.tsx
- wren-ui/src/components/pages/home/promptThread/index.tsx
- wren-ui/src/pages/modeling.tsx
For ask candidates
- Display a saved view mark in the search results, indicating to users that they have previously asked a similar question and saved the view.
For threads
- Display a saved view mark in thread details, informing users that the thread was created based on a saved view.
For modeling page
- Add a query parameter `?viewId=x&openMetadata=true` to automatically open the view metadata drawer upon navigation.
> feat(wren-ui): Offer view result for similar questions

- wren-ai-service/demo/sample_dataset/ecommerce2_duckdb_mdl.json
- wren-ai-service/demo/sample_dataset/ecommerce_duckdb_mdl.json
- wren-ai-service/demo/utils.py
- wren-ai-service/src/pipelines/ask/followup_generation_pipeline.py
> refine ai pipelines

- wren-ui/migrations/20240327030000_create_ask_table.js
- wren-ui/migrations/20240418000000_update_project_table_pg.js
- wren-ui/migrations/20240530062133_update_project_table.js
- wren-ui/migrations/20240530062809_transfer_project_table_data.js
- wren-ui/migrations/20240530105955_drop_project_table_columns.js
- wren-ui/migrations/20240531085916_transfer_model_properties.js
- wren-ui/src/apollo/server/adaptors/ibisAdaptor.ts
- wren-ui/src/apollo/server/connectors/bqConnector.ts
- wren-ui/src/apollo/server/factories/bqStrategy.ts
- wren-ui/src/apollo/server/factories/duckdbStrategy.ts
- wren-ui/src/apollo/server/factories/postgresStrategy.ts
- wren-ui/src/apollo/server/mdl/mdlBuilder.ts
- wren-ui/src/apollo/server/mdl/test/mdlBuilder.test.ts
- wren-ui/src/apollo/server/mdl/type.ts
- wren-ui/src/apollo/server/repositories/projectRepository.ts
- wren-ui/src/apollo/server/resolvers/modelResolver.ts
- wren-ui/src/apollo/server/resolvers/projectResolver.ts
- wren-ui/src/apollo/server/services/askingService.ts
- wren-ui/src/apollo/server/services/modelService.ts
- wren-ui/src/apollo/server/services/projectService.ts
- wren-ui/src/apollo/server/services/queryService.ts
- wrap data source connection related columns(host, port, ...) with a new column "connection_info"
- use `tableReference` in MDL manifest instead of refSql (ref: Wren Engine [PR](https://github.com/Canner/wren-engine/pull/491)). This will benefit performance for small queries and no longer have to deal with SQL format.
> Chore: refactor database schema to reflect how we use them.

- wren-ai-service/src/__main__.py
- wren-ai-service/src/web/development.py
- wren-ai-service/tests/locust/locustfile.py
This PR aims to move the development-related Web API to a separate router, which can be enabled via an environment variable. When the environment is set to `dev`, FastAPI will display these APIs.
- when env is dev
- when env is not dev
> chore(wren-ai-service): move the development purpose API to the development router

- wren-ui/e2e/commonTests/home.ts
- wren-ui/e2e/commonTests/modeling.ts
- wren-ui/e2e/commonTests/onboarding.ts
- wren-ui/e2e/specs/connectBigQuery.spec.ts
- wren-ui/e2e/specs/connectDuckDB.spec.ts
- wren-ui/e2e/specs/connectPostgreSQL.spec.ts
- wren-ui/e2e/specs/connectSampleECommerce.spec.ts
- wren-ui/e2e/specs/connectSampleNBA.spec.ts
- wren-ui/playwright.config.ts
- wren-ui/src/components/diagram/customNode/ModelNode.tsx
- wren-ui/src/components/diagram/customNode/ViewNode.tsx
- wren-ui/src/components/modals/RelationModal.tsx
- wren-ui/src/components/pages/home/prompt/Result.tsx
- wren-ui/src/components/pages/modeling/metadata/EditBasicMetadata.tsx
- wren-ui/src/components/pages/modeling/metadata/ModelMetadata.tsx
- wren-ui/src/components/pages/modeling/metadata/ViewMetadata.tsx
- wren-ui/src/components/selectors/CombineFieldSelector.tsx
- wren-ui/src/components/selectors/DescriptiveSelector.tsx
- wren-ui/src/components/selectors/Selector.tsx
- wren-ui/src/components/selectors/lineageSelector/FieldSelect.tsx
- wren-ui/src/components/selectors/lineageSelector/index.tsx
- wren-ui/src/hooks/useCombineFieldOptions.tsx
- add some basic checks for the sample datasets
- add save recommended relationships test
- Adjust UI style and add **data-testid**
- For data source
- add save recommended relationships test
- For sample datasets
- model CRUD test
- relationship CRUD tests
- update model metadata test
- save as view test (include check offer view result)
- update view metadata test
- check deploy status tests (Synced & Undeployed changes)
- execute deploy MDL test
- Add calculated field CRUD test for NBA sample dataset
```bash
➜   yarn test:e2e
yarn run v1.22.19
warning ../../../../package.json: No license field
warning ../../../../package.json: No license field
[WebServer]  ⚠ Invalid next.config.js options detected:
[WebServer]  ⚠     Unrecognized key(s) in object: 'lessVarsFilePath', …
```
> feat(wren-ui/e2e): add E2E basic check

- wren-ai-service/poetry.lock
- wren-ai-service/pyproject.toml
- wren-ai-service/src/__main__.py
- small refactor to `src/__main__.py`
- upgrade uvicorn version so we don't need gunicorn in the future: https://www.uvicorn.org/release-notes/#0300-2024-05-28
> small refactor and upgrade uvicorn version to allow process manager

- deployment/kustomizations/base/cm.yaml
- deployment/kustomizations/base/deploy-wren-ai-service.yaml
- deployment/kustomizations/patches/cm.yaml
WORKERS required for the deploy-wren-ai-service.yaml
wren-engine-svc is the correct dns name in k8s
> WORKERS & wren-engine-svc

- wren-ai-service/Makefile
I encountered an issue as follows when executing `make demo` command to start the demo-site streamlit app.
```zsh
✦2 ➜ make demo  
make: `demo' is up to date.
```
and the root cause is having a same-name folder over there. thus, need to declare the demo in the .PHONY
See also:
- https://stackoverflow.com/questions/3931741/why-does-make-think-the-target-is-up-to-date
- https://stackoverflow.com/questions/2145590/what-is-the-purpose-of-phony-in-a-makefile
> fix(wren-ai-sevice): phony demo folder

- docker/.env.example
- docker/docker-compose-dev.yaml
- wren-ui/src/apollo/server/adaptors/ibisAdaptor.ts
- wren-ui/src/apollo/server/models/model.ts
- wren-ui/src/apollo/server/resolvers/modelResolver.ts
- wren-ui/src/apollo/server/schema.ts
- wren-ui/src/apollo/server/services/askingService.ts
- wren-ui/src/apollo/server/services/queryService.ts
support dry run in preview API
```
mutation PreviewSql($data: PreviewSQLDataInput) { 
previewSql(data: $data) 
}
{
"data": {
"dryRun": true,
"limit": 1,
"sql": "select * from public.orders"
}
}
```
```
{
"data": {
"previewSql": {
"dryRun": true
}
}
}
```
> Feature: support dry run in preview API

- wren-ui/src/apollo/server/adaptors/ibisAdaptor.ts
- wren-ui/src/apollo/server/adaptors/wrenEngineAdaptor.ts
- wren-ui/src/apollo/server/resolvers/modelResolver.ts
- wren-ui/src/apollo/server/services/queryService.ts
- wren-ui/src/apollo/server/utils/error.ts
- Throw an GraphQL error  back to the client  instead of returning false
- The GraphQL error contains the error code DRY_RUN_ERROR and the error message from ibis/wren-engine back to the client
```
{
"errors": [
{
"locations": [
{
"line": 1,
"column": 51
}
],
"path": [
"previewSql"
],
"message": "Exception: <class 'psycopg2.errors.UndefinedTable'>, message: relation \"public_order\" does not exist\nLINE 1: ...hic5g3ffz553y AS SELECT tmp.* FROM (SELECT * FROM public_ord...\n                                                             ^\n",
"extensions": {
"code": "DRY_RUN_ERROR",
"message": "Exception: <class 'psycopg2.errors.UndefinedTable'>, message: relation \"public_order\" does not exist\nLINE 1: ...hic5g3ffz553y AS SELECT tmp.* FROM (SELECT * FROM public_ord...\n …
```
> Fix(wren-ui): fix previewSql mutation for doing dry run

- wren-ui/migrations/20240610070534_create_schema_change_table.js
- wren-ui/src/apollo/server/managers/dataSourceSchemaDetector.ts
- wren-ui/src/apollo/server/repositories/modelColumnRepository.ts
- wren-ui/src/apollo/server/repositories/modelRepository.ts
- wren-ui/src/apollo/server/repositories/schemaChangeRepository.ts
- wren-ui/src/apollo/server/resolvers.ts
- wren-ui/src/apollo/server/resolvers/projectResolver.ts
- wren-ui/src/apollo/server/schema.ts
- wren-ui/src/apollo/server/types/context.ts
- wren-ui/src/pages/api/graphql.ts
New PR from #339 (The old PR closed because it's base branch has been merged & deleted)
```graphql
query SchemaChange {
schemaChange {
deletedTables
deletedColumns
modifiedColumns
}
}
```
```graphql
mutation Mutation {
triggerDataSourceDetection
}
```
```graphql
enum SchemaChangeType {
DELETED_TABLES
DELETED_COLUMNS
MODIFIED_COLUMNS
}
input ResolveSchemaChangeWhereInput {
type: SchemaChangeType!
}
mutation Mutation($where: ResolveSchemaChangeWhereInput!) {
resolveSchemaChange(where: $where)
}
```
> feat(wren-ui): Detects schema change - table & column

- wren-ui/.env.test
- wren-ui/e2e/README.md
- wren-ui/e2e/commonTests/modeling.ts
- wren-ui/e2e/specs/connectSampleECommerce.spec.ts
- wren-ui/e2e/specs/connectSampleNBA.spec.ts
- wren-ui/playwright.config.ts
- wren-ui/src/components/sidebar/modeling/ModelTree.tsx
- Add calculated fields CRUD test for the E-commerce sample dataset
- Add calculated fields CRUD test for the E-commerce sample dataset
- Extract add and delete calculated field codes as a common function
```sh
➜  wren-ui git:(feature/e2e-e-commerce) yarn test:e2e
yarn run v1.22.19
warning ../../../../package.json: No license field
warning ../../../../package.json: No license field
[WebServer]  ⚠ Invalid next.config.js options detected:
[WebServer]  ⚠     Unrecognized key(s) in object: 'lessVarsFilePath', 'lessVarsFilePathAppendToEndOfContent'
⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
[WebServer]  ⚠ "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
Running 37 tests using 1 worker
[setup db] › …
```
> feat(wren-ui/e2e): Add calculated fields CRUD test for E-commerce sample dataset

- wren-ui/src/apollo/client/graphql/__types__.ts
- wren-ui/src/apollo/client/graphql/dataSource.generated.ts
- wren-ui/src/apollo/client/graphql/dataSource.ts
- wren-ui/src/apollo/server/managers/dataSourceSchemaDetector.ts
- wren-ui/src/apollo/server/repositories/modelColumnRepository.ts
- wren-ui/src/apollo/server/repositories/relationshipRepository.ts
- wren-ui/src/apollo/server/resolvers/modelResolver.ts
- wren-ui/src/apollo/server/resolvers/projectResolver.ts
- wren-ui/src/apollo/server/schema.ts
- wren-ui/src/apollo/server/utils/model.ts
- wren-ui/src/components/modals/SchemaChangeModal.tsx
- wren-ui/src/components/pages/modeling/form/ModelForm.tsx
- wren-ui/src/components/sidebar/modeling/ModelTree.tsx
- wren-ui/src/styles/components/alert.less
- wren-ui/src/styles/components/table.less
- wren-ui/src/styles/components/tag.less
- List affected calculated fields & Relationships
- Update resolveSchemaChange function
The change column of the database is used to save data that is different from the source. The basic three changes of schema change can be known by comparing the change column data with the Model and Model columns data.
As we know, both Calculated fields and Relationships are created by selecting the column of the Model, and are related to the Column. Therefore, the phase 2 we want to support will be affected or have calculated fields and relationships that use the changed Column listed.
- List affected calculated fields & Relationships
- Delete all affected columns, calculated fields, and relationships to resolve schema change
- Fix update model columns related issues
- No expand icon if there are no …
> feat(wren-ui): Support schema change phase 2

- wren-ui/public/images/dataSource/clickhouse.svg
- wren-ui/src/apollo/client/graphql/__types__.ts
- wren-ui/src/apollo/server/adaptors/ibisAdaptor.ts
- wren-ui/src/apollo/server/adaptors/tests/ibisAdaptor.test.ts
- wren-ui/src/apollo/server/config.ts
- wren-ui/src/apollo/server/dataSource.ts
- wren-ui/src/apollo/server/repositories/projectRepository.ts
- wren-ui/src/apollo/server/schema.ts
- wren-ui/src/apollo/server/services/queryService.ts
- wren-ui/src/apollo/server/types/dataSource.ts
- wren-ui/src/components/pages/setup/dataSources/ClickHouseProperties.tsx
- wren-ui/src/components/pages/setup/utils.tsx
- wren-ui/src/utils/enum/dataSources.ts
Support ClickHouse data source
> Feature: Support ClickHouse data source

- wren-ai-service/src/force_deploy.py
- wren-ai-service/src/providers/embedder/azure_openai.py
- wren-ai-service/src/providers/embedder/ollama.py
- wren-ai-service/src/providers/embedder/openai.py
- wren-ai-service/src/providers/llm/azure_openai.py
- wren-ai-service/src/providers/llm/ollama.py
- wren-ai-service/src/providers/llm/openai.py
- wren-ai-service/src/utils.py
- automatically remove trailing / for urls in env vars
- fix azure open ai llm issue
- fix auto redeploy issue
> minor update for ai-service

- wren-ui/src/components/pages/home/thread/feedback/AdjustmentSideFloat.tsx
- wren-ui/src/components/pages/home/thread/feedback/FeedbackSideFloat.tsx
- wren-ui/src/components/pages/home/thread/feedback/ReferenceSideFloat.tsx
- wren-ui/src/components/pages/home/thread/feedback/ReviewDrawer.tsx
- wren-ui/src/components/pages/home/thread/feedback/index.tsx
- wren-ui/src/components/pages/home/thread/index.tsx
- wren-ui/src/styles/utilities/spacing.less
- wren-ui/src/styles/utilities/text.less
- Add Pending Feedback Fixed Block
- Name: FeedbackSideFloat
- Review Feedback Drawer, name: ReviewDrawer
- Collapse feature
- Edit feature
- Swap to Input if clicking edit icon
- Remove revised in reference if clicking delete icon
- Interact with References UI
> feat(wren-ui): Add Pending Feedbacks UI

- wren-ui/src/apollo/client/graphql/__types__.ts
- wren-ui/src/apollo/client/graphql/home.generated.ts
- wren-ui/src/apollo/client/graphql/home.ts
- wren-ui/src/apollo/server/adaptors/wrenAIAdaptor.ts
- wren-ui/src/apollo/server/backgroundTrackers/threadResponseBackgroundTracker.ts
- wren-ui/src/apollo/server/repositories/threadResponseRepository.ts
- wren-ui/src/apollo/server/resolvers.ts
- wren-ui/src/apollo/server/resolvers/askingResolver.ts
- wren-ui/src/apollo/server/schema.ts
- wren-ui/src/apollo/server/services/askingService.ts
- wren-ui/src/components/pages/home/thread/AnswerResult.tsx
- wren-ui/src/components/pages/home/thread/feedback/FeedbackSideFloat.tsx
- wren-ui/src/components/pages/home/thread/feedback/ReferenceSideFloat.tsx
- wren-ui/src/components/pages/home/thread/feedback/ReviewDrawer.tsx
- wren-ui/src/components/pages/home/thread/feedback/index.tsx
- wren-ui/src/components/pages/home/thread/feedback/utils.tsx
- wren-ui/src/components/pages/home/thread/index.tsx
- wren-ui/src/pages/home/[id].tsx
- wren-ui/src/styles/utilities/display.less
- wren-ui/src/styles/utilities/text.less
- wren-ui/src/utils/errorHandler.tsx
- Add `createRegeneratedThreadResponse` API
- Request Structure
```graphql
input CreateThreadResponseCorrectionInput {
id: Int!
stepIndex: Int!
type: ReferenceType!
reference: String!
correction: String!
}
input CreateRegeneratedThreadResponseInput {
responseId: Int!
corrections: [CreateThreadResponseCorrectionInput!]!
}
```
- Response structure refer to Create Thread Response
- ps. client need to fetch Thread Response after Create Adjustment Response.
- Provide adjustment content in Thread & Thread response API
```graphql
type ThreadResponse {
...
question
corrections: [{
id
type
correction
}]
}
```
- Check thread response type if it is an regenerated response.
- Change thread detail original question block to regenerated information.
> feat(wren-ui): Create Regenerated Response API & Add Regenerated Information in Thread Detail UI

- wren-ui/src/components/dataPreview/PreviewData.tsx
- wren-ui/src/components/dataPreview/PreviewDataContent.tsx
- wren-ui/src/components/pages/home/promptThread/CollapseContent.tsx
- Changing step preview empty state
`No Data` to `Sorry, we couldn't find any records that match your search criteria.`
> feat(wren-ui): Modify step's preview data empty state wording

- wren-ui/src/apollo/server/services/askingService.ts
- wren-ui/src/components/editor/CodeBlock.tsx
- wren-ui/src/components/pages/home/thread/CollapseContent.tsx
- wren-ui/src/components/pages/home/thread/StepContent.tsx
- wren-ui/src/components/pages/home/thread/feedback/ReferenceSideFloat.tsx
- wren-ui/src/components/pages/home/thread/feedback/SQLHighlight.tsx
- wren-ui/src/components/pages/home/thread/feedback/index.tsx
- wren-ui/src/components/pages/home/thread/index.tsx
Add SQL highlight component
Wren AI provides new image: `feedback-v6`, group by id issue fixed
Waiting for Wren Engine to fix the relation key line issue
https://github.com/Canner/wren-engine/issues/683
**23 JUL Updated**: According to Wren Engine, the issue is not a bug, they will provide `nodeLocation` for criteria.
> feat(wren-ui): SQL Highlight References

- wren-ui/src/apollo/server/adaptors/ibisAdaptor.ts
- wren-ui/src/apollo/server/adaptors/wrenEngineAdaptor.ts
- wren-ui/src/apollo/server/resolvers/modelResolver.ts
- wren-ui/src/apollo/server/utils/error.ts
Fix issue https://github.com/Canner/WrenAI/issues/520 
We previously used Wren Engine to do dry-plan. Now, when the data source is not DuckDB, we use ibis server for dry-plan.
> Fix(wren-ui): Fix getting incorrect native sql issue

- wren-ui/src/components/table/MultiSelectBox.tsx
In #491 using onChange to handle select all & deselect all click,
the if condition didn't bypass select one click successfully (it happens when the `selectedKeys` already had 1 key), causing onSelect & onChange to update `selectedKeys` at the same time, so there are duplicated keys inside.
> fix(wren-ui): Fix select models duplicated keys issue

- wren-ai-service/eval/evaluation.py
- wren-ai-service/eval/metrics/column.py
This PR aims to add error handling to the evaluation process to prevent errors from affecting the results and also add a condition to avoid the error for Accuracy Metric. Additionally, it introduces a "failed count" metadata field into the summary trace, which will help us easily track the number of successful and failed traces.
> fix(wren-ai-service): error handling for evaluation process

- wren-ui/src/apollo/server/adaptors/ibisAdaptor.ts
- wren-ui/src/apollo/server/adaptors/wrenEngineAdaptor.ts
- wren-ui/src/apollo/server/resolvers/askingResolver.ts
- wren-ui/src/apollo/server/resolvers/modelResolver.ts
- wren-ui/src/apollo/server/resolvers/projectResolver.ts
- wren-ui/src/apollo/server/services/askingService.ts
- wren-ui/src/apollo/server/services/deployService.ts
- wren-ui/src/apollo/server/services/tests/deployService.test.ts
- wren-ui/src/apollo/server/telemetry/telemetry.ts
- wren-ui/src/apollo/server/types/context.ts
- wren-ui/src/apollo/server/utils/error.ts
- wren-ui/src/pages/api/graphql.ts
- refine telemetry: rename event names and add postfix with success or not.
- hide dry-run error log due to happening too many times when ai service is doing SQL validation.
> Chore: adjust telemetry and logger

- .github/workflows/pull-request-title-validator.yaml
This PR aims to add a GitHub workflow to avoid the inconsistency PR title causes missing commits in release details for a tag. and we will use https://github.com/kontrolplane/pull-request-title-validator to address this issue.
- The title matches the scopes
- The title doesn't matche the scopes
> chore(wren-ai-service): pr title validation

- wren-ai-service/eval/.env.example
- wren-ai-service/eval/evaluation.py
- wren-ai-service/eval/metrics/column.py
- wren-ai-service/eval/prediction.py
This PR addresses error handling for failed metrics computation and includes the pipeline name in the evaluation results.
> fix(wren-ai-service): error handling for accuracy metric to avoid the select all query failed

- wren-ai-service/entrypoint.sh
This PR aims to extend the timeout, as the AI service startup process sometimes requires additional time. It also moves the checking mechanism that activates when force deployment is enabled.
> fix(wren-ai-service): expend the timeout and move the waiting check mechanism when force deploying

- wren-ai-service/eval/preparation.py
- Deal with models and columns without `properties` keys
- Use csv read/write functions can escape commas within quotes, prevent descriptions containing commas breaking the csv structure. 
- Note: Still recommend to save the output csv file as xlsx file, if expecting users to edit descriptions with Excel.
> chore(wren-ai-service): Refine mdl preparation script

- .github/dependabot.yaml
This PR aims to update the Dependabot PR commit message to 'wren-ai-service,' eliminating the need for manual modifications for each PR. Thanks to @grieve54706 for suggesting this great feature!
See also:
-  https://github.com/Canner/wren-engine/blob/main/.github/dependabot.yml
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
> chore(wren-ai-service): custom dependabot commit message and labels

- docker/docker-compose-dev.yaml
remove wren-ui from `depends_on` in wren-ai-service
> chore(wren-ai-service): fix docker-compose-dev.yaml

- wren-ui/src/components/pages/setup/ButtonItem.tsx
UI layout is broken when selecting a sample dataset
https://github.com/user-attachments/assets/7edff7d7-452d-4a79-bb8e-97431497f5e7
> fix(wren-ui): UI layout is broken when selecting a sample dataset

- wren-ai-service/src/utils.py
- wren-ai-service/src/web/v1/services/ask.py
- wren-ai-service/src/web/v1/services/ask_details.py
- wren-ai-service/src/web/v1/services/indexing.py
- wren-ai-service/tests/pytest/test_utils.py
Before this PR, we used the project ID as the user ID for Langfuse. In our team discussion, we decided to include the project ID in the metadata and introduce an optional user_id attribute for API requests. We also ensured that the logic remains consistent.
> feat(wren-ai-service): optional attribute user_id for Langfuse metadata

- .github/workflows/ai-service-release-stable-image.yaml
This PR aims to fix #632. and it has been reproduced in [here](https://github.com/Canner/WrenAI/actions/runs/10678532991/job/29595791499). the problem is that we don't fetch the latest git ref in checkout action. refer to https://github.com/actions/checkout/issues/1327
- see https://github.com/Canner/WrenAI/actions/runs/10678858613/job/29596820200, for the details of the fix
> fix(wren-ai-service): correct the wrong version in docker image

- wren-ai-service/src/pipelines/ask/retrieval.py
This PR updates the system prompt used for table columns selection in the AI service. The changes aim to provide clearer instructions and a more structured JSON format for the AI's response.
1. Refined the task description to be more concise and focused.
2. Added a structured "INSTRUCTIONS" section with step-by-step guidance.
3. Updated the "FINAL ANSWER FORMAT" section to require a more detailed JSON structure:
- Each table now includes a list of reasons (`chain_of_thought_reasoning`) for column selection.
- The reasoning is now presented as a list of individual points rather than a single string.
4. Added an "ADDITIONAL NOTES" section to emphasize important requirements.
5. Removed unnecessary motivational language and focused on clear, professional instructions.
- Improved clarity and …
> feat(wren-ai-service): update the system prompt for table columns selection to provide clear instructions and expected JSON format.

- wren-ai-service/src/pipelines/indexing/indexing.py
- wren-ai-service/src/web/v1/services/ask.py
- wren-ai-service/tests/pytest/pipelines/test_view_chunker.py
This PR enhances the view chunking process to include historical queries, improving the context for follow-up questions in the AI service.
1. Renamed `ViewConverter` to `ViewChunker` for clarity.
2. Updated `ViewChunker` to include historical queries in the content:
- Now combines `historical_queries` with the current question.
- Example JSON configuration:
```yaml
{
"views": [
{
"name": "book",
"statement": "SELECT * FROM book where created_at = 2020",
"properties": {
"question": "in 2020",
"summary": "Retrieve the number of books in 2020",
"viewId": "fake-id-1",
"historical_queries": [
"Retrieve the number of books"
]
}
}
]
}
```
3. Modified `AskService` to use a combined query for retrieval:
- Includes history summary and current query when available.
5. Refactored `Indexing` class to …
> feat(wren-ai-service): add historical queries in view chunk for follow-up question

- wren-ai-service/src/pipelines/indexing/indexing.py
This PR addresses an issue with the handling of nested properties in the `properties` dictionary.
```json
{
"models": [
{
"name": "test",
"columns": [
{
"name": "test",
"type": "test",
"properties": {
"displayName": "test",
"description": "test",
"nestedDisplayName.city.tree": "Tree",
"nestedDescription.city.tree": "The customer City, where ...",
"nestedDisplayName.city.author": "The Author",
"nestedDescription.city.author": "The Author of the city, where ...",
"nestedDescription.city.author.name": "The name of the author"
}
}
]
}
],
"views": [],
"relationships": [],
"metrics": []
}
```
```python
{
'type': 'TABLE_COLUMNS',
'columns': [
{
'type': 'COLUMN',
'comment': '-- {"alias":"test","description":"test","nested_columns":{"nestedDisplayName.city.tree":"Tree","nestedDescription.city.tree" …
```
> feat(wren-ai-service): add all nested columns properties into column comment

- wren-ui/README.md
Provide local setup instruction and FAQ
> Chore(wren-ui): update wren-ui readme

- wren-ai-service/poetry.lock
- wren-ai-service/pyproject.toml
- wren-ai-service/src/providers/llm/openai.py
allow auto-refresh expired vertexai credentials
> chore(wren-ai-service): sql2answer-minor-update

- wren-ai-service/demo/utils.py
- wren-ai-service/src/pipelines/retrieval/retrieval.py
1. fix overriding config.yaml in demo
2. fix table column selection by incorporating struct as column; also we may need to use gpt-4o in this case
> chore(wren-ai-service): minor updates

- wren-launcher/commands/launch.go
Hi Team, attaching the screenshot that shows keyboard interrupt to terminate the process
> fix(wren-launcher): for Installation should stop when exiting the launcher

- wren-ai-service/config.example.yaml
- wren-ai-service/src/globals.py
- wren-ai-service/src/pipelines/generation/semantics_description.py
- wren-ai-service/src/web/v1/routers/__init__.py
- wren-ai-service/src/web/v1/routers/semantics_description.py
- wren-ai-service/src/web/v1/services/semantics_description.py
- wren-ai-service/tests/pytest/services/test_semantics_description.py
This PR introduces the `SemanticsDescription` service, which provides endpoints for generating and optimizing semantic descriptions based on user prompts and selected models.
**Endpoint:** `POST /v1/semantics-descriptions`
**Request Body:**
```json
{
"selected_models": ["model1", "model2"],
"user_prompt": "Describe the data model",
"mdl": "..."
}
```
**Response:**
```json
{
"id": "unique_id",
}
```
**Endpoint:** `GET /v1/semantics-descriptions/{id}`
**Path Parameter:**
- `id`: Unique identifier of the semantic description resource
**Response:**
```json
{
"id":"unique_id",
"status":"finished",
"response":{
"model1":{
"name":"model1",
"columns":[
{
"name":"col1",
"properties":{
"description":"Unique identifier for each record in the example model."
}
}
],
"properties":{
"description":"This …
```
> feat(wren-ai-service): semantics description pipeline to generate or optimize the user description

- wren-ai-service/config.example.yaml
- wren-ai-service/src/globals.py
- wren-ai-service/src/pipelines/generation/relationship_recommendation.py
- wren-ai-service/src/pipelines/prototype/relationship_recommendation.py
- wren-ai-service/src/web/v1/routers/__init__.py
- wren-ai-service/src/web/v1/routers/relationship_recommendation.py
- wren-ai-service/src/web/v1/services/relationship_recommendation.py
- wren-ai-service/tests/pytest/services/test_relationship_recommendation.py
This PR introduces the `RelationshipRecommendation` service and corresponding router, which provide endpoints for generating and retrieving relationship recommendations based on Model Definition Language (MDL) input.
> [!IMPORTANT] 
> This PR based on #716, thus before it to be merged, dont merge this PR. thanks!
**Endpoint:** `POST /v1/relationship-recommendations`
**Request Body:**
```json
{
"mdl": "{ ... }"  // JSON string of the MDL (Model Definition Language)
}
```
**Response:**
```json
{
"id": "unique-uuid"
}
```
**Endpoint:** `GET /v1/relationship-recommendations/{id}`
**Path Parameter:**
- `id`: Unique identifier of the relationship recommendation resource
**Response:**
```json
{
"id":"unique-uuid",
"status":"generating", // "finished" "failed"
"response":{
"recommendations":[
{ …
```
> feat(wren-ai-service): relationships recommendation pipeline to produce the relationships for users easily establish 

- wren-ui/src/components/diagram/index.tsx
This PR fixes #713 .
Initially, I tried updating the **ReactFlow** library to version 12, hoping that would solve the issue, but it didn’t work. After further investigation, I found [this discussion](https://github.com/xyflow/xyflow/discussions/3912) detailing our exact use case. The [response from the maintainer](https://github.com/xyflow/xyflow/discussions/3912#discussioncomment-8476769) identified the underlying cause: the problem stems from the **d3 zoom** library that **ReactFlow** uses under the hood. 
When disabling pointer events (as suggested), it allowed me to detect clicks, but this also disabled the drag functionality, which isn’t ideal for our use case.
To resolve this, I implemented a workaround that triggers a `mousedown` event programmatically whenever a click occurs …
> Trigger a mouse event every time the ReactFlow component is clicked

- .github/workflows/ai-service-test.yaml
We encountered an issue similar to the one documented in [this GitHub Actions run](https://github.com/Canner/WrenAI/actions/runs/11230538407/job/31218085695). To address this, we have added the `workflow_dispatch` event to the GitHub Actions workflow. This change allows maintainers to manually trigger the `pytest` job from the Actions page, enabling contributors to validate their changes more effectively.
This enhancement provides a temporary solution to the issue at hand. In the future, we may explore additional methods to improve our testing workflow further.
> chore(wren-ai-service): manual running pytest to avoid auth issue from forked repo

- wren-ai-service/src/pipelines/generation/semantics_description.py
- wren-ai-service/src/web/v1/services/relationship_recommendation.py
- wren-ai-service/src/web/v1/services/semantics_description.py
- wren-ai-service/tests/pytest/services/test_relationship_recommendation.py
- wren-ai-service/tests/pytest/services/test_semantics_description.py
This pull request introduces several changes to enhance error handling and data processing within the `wren-ai-service` module. The key updates include adding new error codes, improving exception handling, and refining data extraction methods.
Added following error codes in relationship recommendation and semantics description services:
- MDL_PARSE_ERROR: it means that the MDL is not valid by the JSON format
- RESOURCE_NOT_FOUND: it means that the ID didn't target a specified resource.
* Added a new helper function `remove_relation_columns` to filter out columns with a relationship property during data extraction.
```json
{
"selected_models": [
"example", "example2"
],
"user_prompt": "demo prompt",
"mdl": "{\"catalog\":\"example\",\"schema\":\"example\",\"models\":[{\"name\":\"example\",\" …
```
> feat(wren-ai-service): remove relation columns before generating semantics description and error code enhancement

- wren-ui/src/apollo/server/mdl/mdlBuilder.ts
This PR fixes #706 
The sync status on the modeling page shows "Undeployed changes" after completing the onboarding process, even though it should display "synced" with a green check.
As the issue mentioned what would be the solution so I first tired to reproduct the issue and apply sorting to models, columns and relations, again tested and it worked.
After running updated code, this is what I got
Let me know your thoughts, and feel free to merge this PR if you’re satisfied with the solution.
> Update MDLBuilder constructor to sort input columns, models and relations based on their key.

- wren-ai-service/src/pipelines/generation/followup_sql_generation.py
- wren-ai-service/src/pipelines/generation/relationship_recommendation.py
- wren-ai-service/src/pipelines/generation/semantics_description.py
- wren-ai-service/src/pipelines/generation/sql_answer.py
- wren-ai-service/src/pipelines/generation/sql_breakdown.py
- wren-ai-service/src/pipelines/generation/sql_correction.py
- wren-ai-service/src/pipelines/generation/sql_expansion.py
- wren-ai-service/src/pipelines/generation/sql_explanation.py
- wren-ai-service/src/pipelines/generation/sql_generation.py
- wren-ai-service/src/pipelines/generation/sql_regeneration.py
- wren-ai-service/src/pipelines/generation/sql_summary.py
- wren-ai-service/src/pipelines/retrieval/retrieval.py
- wren-ai-service/src/web/v1/services/ask.py
- wren-ai-service/src/web/v1/services/ask_details.py
- wren-ai-service/src/web/v1/services/sql_expansion.py
- wren-ai-service/tests/pytest/pipelines/test_ask_details.py
- wren-ai-service/tests/pytest/services/mocks.py
- allow generating candidates in generating phase
- stablize generating multilingual output
- fix time issue
> chore(wren-ai-service): refine sql generation

- wren-ui/migrations/20241021073019_update_project_language.js
- wren-ui/src/apollo/client/graphql/__types__.ts
- wren-ui/src/apollo/client/graphql/settings.generated.ts
- wren-ui/src/apollo/client/graphql/settings.ts
- wren-ui/src/apollo/server/adaptors/wrenAIAdaptor.ts
- wren-ui/src/apollo/server/repositories/projectRepository.ts
- wren-ui/src/apollo/server/resolvers.ts
- wren-ui/src/apollo/server/resolvers/askingResolver.ts
- wren-ui/src/apollo/server/resolvers/projectResolver.ts
- wren-ui/src/apollo/server/schema.ts
- wren-ui/src/apollo/server/services/askingService.ts
- wren-ui/src/components/settings/ProjectSettings.tsx
- wren-ui/src/components/settings/index.tsx
- wren-ui/src/utils/language.ts
This feature aims to provide users with a project language setting.
When users ask, the AI service should return the result matching the selected language.
- Provide `UpdateCurrentProject` API to update language
- Add `language` in `Settings` API
- Pass `configurations` to AI service
> feat(wren-ui): Implement project language setting

- docker/README.md
I found some dead links in [`/docker/README.md`](https://github.com/Canner/WrenAI/blob/0b2e9af078e146df187e80176cdce09f4c48bfa5/docker/README.md) and I decided to fix them. Please note that I used the _absolute_ link, because such approach was used in case of `wren-engine
/example`.
> docs: update dead links in `docker/README.md`

- wren-ui/src/hooks/useSetupConnection.tsx
Fix #712 
I have resolved the issue where the password field appeared empty on the Data Source Settings page for connected ClickHouse, MSSQL, MySQL, Postgres, and Trino data source. Your review would be greatly appreciated, thanks in advance!
> fix(wren-ui): Displayed password placeholder for Data Source Settings

- wren-ui/src/components/pages/home/prompt/index.tsx
- wren-ui/src/hooks/useAskPrompt.tsx
- wren-ui/src/pages/home/[id].tsx
- wren-ui/src/pages/home/index.tsx
- Stop continuing polling if the user clicks candidate first when generating results
- Stop polling & close prompt results if users change threads
> fix(wren-ui): Stop polling if users click candidate during generating

- wren-ai-service/src/pipelines/generation/relationship_recommendation.py
This PR updates the relationship recommendation pipeline. The changes focus on improving the pipeline's functionality, observability, and output structure.
1. Added Observability:
- Introduced `@observe` decorators to key functions for improved monitoring and debugging.
2. New `cleaned_models` Function:
- Added a function to filter out existing relationships from the input models.
3. Updated Prompt Generation:
- Modified the `prompt` function to use the cleaned models.
4. Enhanced System Prompt:
- Significantly updated the system prompt to provide more specific guidelines for relationship recommendations.
- Changed the output structure to include more detailed relationship information.
5. Updated `ModelRelationship` Class:
- Revised the structure to match the new relationship …
> feat(wren-ai-service): adjust relation recommendation pipeline prompt and output spec

- wren-ui/src/components/pages/setup/DefineRelations.tsx
- Show info message if there are no recommended relationships
- Not show info message if there are recommended relationships
- Disable the Finish button when still loading data
> feat(wren-ui): show info message if there are no recommended relationships

- wren-ui/README.md
This PR updates the dead link in:
https://github.com/Canner/WrenAI/blob/c9706b52c455ea811b77fb80055ded76ef4144ad/wren-ui/README.md?plain=1#L154
Similar to #769.
> docs: update dead link in `wren-ui/README.md`

- .github/workflows/ui-release-image-stable.yaml
tag wren ui before releasing stable image
> chore(wren-ui): tag wren ui before releasing stable image

- .github/workflows/ui-release-image-stable.yaml
fix sed command in the Github action workflow
- sed -i '' not suitable on linux based OS
> chore(wren-ui): fix sed command in the Github action workflow

- wren-ui/src/apollo/server/repositories/projectRepository.ts
Fix #800 
Identified that the issue was caused by a typo in the "connection info" key in the transformToDBData function, which should be in snake_case. Your review would be greatly appreciated, thanks in advance!
https://github.com/user-attachments/assets/8ae3915c-85b3-47af-98f7-d0774d38a650
https://github.com/user-attachments/assets/0518920a-776f-40cf-a6da-8d7932eef894
> fix(wren-ui): Resolved data source update bug

- wren-ui/src/components/learning/guide/stories.tsx
- wren-ui/src/components/pages/setup/dataSources/ClickHouseProperties.tsx
- wren-ui/src/components/pages/setup/dataSources/MySQLProperties.tsx
- wren-ui/src/components/pages/setup/dataSources/PostgreSQLProperties.tsx
- wren-ui/src/components/pages/setup/dataSources/SQLServerProperties.tsx
- wren-ui/src/components/pages/setup/dataSources/TrinoProperties.tsx
- wren-ui/src/utils/error/dictionary.ts
- wren-ui/src/utils/validator/hostValidator.ts
- wren-ui/src/utils/validator/index.ts
This PR adds validation to the **Host** field in the database connection settings to guide users on correctly setting up a local database in a Docker environment.
- Add frontend validation for the **Host** field.
- Apply ClickHouse, MySQL, PostgreSQL, SQLServer, Trino
Show the error message - `Invalid host. Use 'host.docker.internal' on macOS/Windows to connect to the local database.` when a user fills **localhost** or **127.0.0.1** value as the host.
> chore(wren-ui): improve host validator for data sources

- wren-ai-service/src/pipelines/common.py
- wren-ai-service/src/providers/engine/wren.py
- wren-ui/src/apollo/server/resolvers/modelResolver.ts
- wren-ui/src/apollo/server/services/queryService.ts
Add correlation ID from the ibis server to the Langfuse.
The AI team usually provides the issues from the Langfuse, if we want to find the ibis log for the issue, we need to find it by time, and the time is not completely correct.
The correlation ID is from the ibis-server. The AI service gets data and the correlation ID through the web API, and the AI service sends Langfuse logs. So, we must explain the correlation ID and return it to the AI service.
> chore(wren-ai-service): add correlation ID to langfuse

- wren-ai-service/config.example.yaml
- wren-ai-service/src/globals.py
- wren-ai-service/src/pipelines/generation/question_recommendation.py
- wren-ai-service/src/web/v1/routers/__init__.py
- wren-ai-service/src/web/v1/routers/question_recommendation.py
- wren-ai-service/src/web/v1/routers/relationship_recommendation.py
- wren-ai-service/src/web/v1/services/__init__.py
- wren-ai-service/src/web/v1/services/question_recommendation.py
- wren-ai-service/src/web/v1/services/relationship_recommendation.py
- wren-ai-service/src/web/v1/services/semantics_description.py
- wren-ai-service/tests/pytest/services/test_relationship_recommendation.py
- wren-ai-service/tests/pytest/services/test_semantics_description.py
This PR introduces a new Question Recommendation feature to the Wren AI Service. 
1. Added `question_recommendation` to the `pipes` configuration in `config.example.yaml`
2. Updated `ServiceContainer` in `src/globals.py` to include `question_recommendation`
3. Added `question_recommendation` router to the main router in `src/web/v1/routers/__init__.py`
4. Implemented the Question Recommendation pipeline, service, and router
The PR introduces two new endpoints for question recommendation:
1. `POST /question-recommendations`
2. `GET /question-recommendations/{id}`
To generate new question recommendations:
```http
POST /question-recommendations
```
```jsonc
{
// JSON string of the MDL (Model Definition Language)
"mdl": "{ ... }",
// Optional list of previous questions
"previous_questions": [ …
```
> feat(wren-ai-service): question recommendation pipeline

- wren-ai-service/src/pipelines/generation/semantics_description.py
- wren-ai-service/src/web/v1/routers/semantics_description.py
- wren-ai-service/src/web/v1/services/semantics_description.py
- wren-ai-service/tests/pytest/services/test_semantics_description.py
This PR introduces improvements to the Semantics Description pipeline by implementing chunked processing and updating error handling:
1. Chunked Processing:
- Added `_chunking` method to process models in smaller batches
- Implemented concurrent processing using `asyncio.gather`
- Default chunk size of 1 model per request
2. Error Handling:
- Modified normalize function to return `{"models": []}` instead of `{}` on JSON decode error
- Enhanced error logging and handling
3. Documentation:
- Updated API documentation to accurately reflect the response structure
- Added detailed examples in the docstring
```python:wren-ai-service/src/web/v1/services/semantics_description.py
def _chunking(self, mdl_dict: dict, request: Input, chunk_size: int = 1) -> list[dict]:
template = {
"user_prompt": …
```
> feat(wren-ai-service): batch processing to produce the semantics description for a large MDL

- docker/.env.example
- wren-ai-service/.env.dev.example
- wren-ai-service/eval/data_curation/app.py
- wren-ai-service/poetry.lock
- wren-ai-service/pyproject.toml
- wren-ai-service/src/__main__.py
- wren-ai-service/src/globals.py
- wren-ai-service/src/pipelines/retrieval/retrieval.py
- wren-ai-service/src/providers/llm/azure_openai.py
- wren-launcher/commands/launch.go
- wren-launcher/config/config.go
1. add env `ALLOW_USING_DB_SCHEMAS_WITHOUT_PRUNING`, default: False
2. use tiktoken library to count tokens of db schemas ddl, and apply the rules of column pruning as follows:
- using gpt-4o or gpt-4o-mini, if token count of db schemas ddl is less than 100k -> column pruning
- using gpt-4o or gpt-4o-mini, if token count of db schemas ddl is greater than or equal to 100k -> no column pruning
- using other llms -> no column pruning, unless ALLOW_USING_DB_SCHEMAS_WITHOUT_PRUNING is True
- by default, ALLOW_USING_DB_SCHEMAS_WITHOUT_PRUNING is False
- in the near future after we accomodate multi-llms, users need to fill in context window size for more intricate control on whether we need column pruning
3. remove gpt-3.5-turbo and gpt-4-turbo
> chore(wren-ai-service): optimize retrieval process

- wren-ai-service/src/pipelines/common.py
This PR updates the text-to-SQL rules to enforce table alias qualification for column names, improving query clarity and preventing ambiguity in generated SQL queries.
Key updates to the SQL generation rules:
- Added rule: "ALWAYS QUALIFY column names with their table name or table alias"
- Modified a few example to mention the matter
Before:
```sql
SELECT SUM(PriceSum) FROM Revenue 
WHERE CAST(PurchaseTimestamp AS TIMESTAMP WITH TIME ZONE) >= ...
```
After:
```sql
SELECT SUM(r.PriceSum) FROM Revenue r 
WHERE CAST(r.PurchaseTimestamp AS TIMESTAMP WITH TIME ZONE) >= ...
```
After the prompt optimization, the sql will use table or alias to avoid column ambiguity, and we could observe the issue whether this issue occurs again.
```sql
SELECT "olist_customers_dataset"."customer_city" AS …
```
> feat(wren-ai-service): prompting to avoid column ambiguity

- wren-ui/src/components/pages/home/promptThread/CollapseContent.tsx
In PR #899, adding `isViewSQL` caused confusion within the `CollapseContent` template condition. This fix introduces `isViewStepSQL` to more clearly separate the conditions.
> fix(wren-ui): Separate view step sql & view full sql condition

- wren-ui/src/components/modals/RelationModal.tsx
- wren-ui/src/components/pages/setup/DefineRelations.tsx
- wren-ui/src/hooks/useSetupRelations.tsx
The user can see the **`This relationship already exists.`** error when editing a relationship in the Define relationships step of onboarding.
Steps to reproduce the behavior:
1. Start onboarding flow
2. Use a database with primary and foreign keys (E.g., [Pagila database](https://neon.tech/docs/import/import-sample-data#pagila-database))
3. Complete the connection to the database, select all tables, and successfully enter the Define relationships step page.
4. After seeing the recommended relationships appear on the table, edit a relationship
5. See **`This relationship already exists.`** error
Will not see the error message when editing a relationship in the Define relationships step of onboarding.
> fix(wren-ui): see an error when editing a relationship in the defined relationships step of onboarding

- wren-ai-service/src/pipelines/generation/relationship_recommendation.py
Updates the relationship generation prompt to remove `MANY_TO_MANY` from the allowed relationship types. The supported relationship types are now limited to:
- `MANY_TO_ONE`
- `ONE_TO_MANY`
- `ONE_TO_ONE`
> feat(wren-ai-service): remove recommending relation type MANY_TO_MANY

- wren-ai-service/src/pipelines/generation/semantics_description.py
- wren-ai-service/src/web/v1/routers/relationship_recommendation.py
- wren-ai-service/src/web/v1/routers/semantics_description.py
- wren-ai-service/src/web/v1/services/semantics_description.py
- wren-ai-service/tests/pytest/services/test_semantics_description.py
This PR enhances the semantics description pipeline with improved model handling, batching capabilities, and API updates.
- Refactored `picked_models` function for better column handling:
- Added `relation_filter` to handle relationship columns
- Introduced `column_formatter` for consistent column structure
- Enhanced model property extraction with default description fields
- Implemented column-based batching strategy with a default size of 50 columns
- Added chunking logic to process large models efficiently:
- Models are processed in chunks while maintaining model integrity
- Each chunk maintains the complete context for accurate description generation
- Added `project_id` field to request models for better tracking
- Updated request/response structures in both semantics description …
> feat(wren-ai-service): column-based batch to generate semantics

- wren-ui/e2e/commonTests/home.ts
- wren-ui/e2e/commonTests/onboarding.ts
- wren-ui/e2e/specs/connectSampleECommerce.spec.ts
- wren-ui/e2e/specs/connectSampleHR.spec.ts
This issue was identified as a navigation change introduced in PR #843, which redirects to the Modeling page after onboarding. Fix #922.
- PostgreSQL
- Trino
> fix(wren-ui/e2e): Update E2E test for navigation change

- wren-ui/src/components/pages/home/prompt/Result.tsx
**This PR fixes #880**
This update ensures that the `viewId` is correctly returned to the user. Previously, only the `sql` was passed with `onSelectResult`. Now, we include the `viewId` with:  
```javascript
onSelectResult && onSelectResult({ sql: result.sql, viewId: result.view?.id });
```  
A video is included to demonstrate that the functionality now works as expected.  
https://github.com/user-attachments/assets/0723833c-37e7-40b3-8c41-5de141bf6c63
Special thanks to @cyyeh for collaborating on this fix and helping bring it to completion!
> Ensure answers correctly indicate their associated view

- wren-ai-service/src/pipelines/generation/relationship_recommendation.py
- wren-ai-service/src/web/v1/routers/relationship_recommendation.py
- wren-ai-service/src/web/v1/routers/semantics_description.py
- wren-ai-service/src/web/v1/services/relationship_recommendation.py
- wren-ai-service/src/web/v1/services/semantics_description.py
- wren-ai-service/tests/pytest/services/test_relationship_recommendation.py
1. Added relationship type validation to filter out unexpected relationship types
- Introduced `RelationType` enum to strictly define valid relationship types (ONE_TO_ONE, ONE_TO_MANY, MANY_TO_ONE)
- Added validation in the `validated()` function to filter out relationships with invalid types
- Updated ModelRelationship to use the RelationType enum for type checking
2. Added language support for relationship recommendations
- Added language parameter throughout the pipeline
- Updated prompt templates to include language configuration
- Made language configurable through the API with a default of "English"
3. Code improvements
- Added proper type hints and validation
- Improved error handling and logging
- Updated API documentation
Before validation:
```json
{
"relationships": [
{"type": …
```
> feat(wren-ai-service): Add Relationship Type Validation and Language Support for semantics description

- wren-ui/src/apollo/server/services/askingService.ts
- wren-ui/src/components/pages/home/prompt/index.tsx
This PR fixes the `summary` property to correctly use the input question when users create a thread from a view. It is related to #928, which addressed issues with creating threads from views.
> fix(wren-ui): Create thread from view summary value change to question

- wren-ai-service/demo/sample_dataset/ecommerce_duckdb_mdl.json
- wren-ai-service/src/core/pipeline.py
- wren-ai-service/src/pipelines/common.py
- wren-ai-service/src/pipelines/generation/data_assistance.py
- wren-ai-service/src/pipelines/generation/followup_sql_generation.py
- wren-ai-service/src/pipelines/generation/intent_classification.py
- wren-ai-service/src/pipelines/generation/question_recommendation.py
- wren-ai-service/src/pipelines/generation/relationship_recommendation.py
- wren-ai-service/src/pipelines/generation/semantics_description.py
- wren-ai-service/src/pipelines/generation/sql_answer.py
- wren-ai-service/src/pipelines/generation/sql_breakdown.py
- wren-ai-service/src/pipelines/generation/sql_correction.py
- wren-ai-service/src/pipelines/generation/sql_expansion.py
- wren-ai-service/src/pipelines/generation/sql_explanation.py
- wren-ai-service/src/pipelines/generation/sql_generation.py
- wren-ai-service/src/pipelines/generation/sql_regeneration.py
- wren-ai-service/src/pipelines/generation/sql_summary.py
- wren-ai-service/src/pipelines/indexing/indexing.py
- wren-ai-service/src/pipelines/retrieval/historical_question.py
- wren-ai-service/src/pipelines/retrieval/retrieval.py
- wren-ai-service/src/web/v1/routers/ask.py
- wren-ai-service/src/web/v1/services/__init__.py
- wren-ai-service/src/web/v1/services/ask.py
- wren-ai-service/src/web/v1/services/ask_details.py
- wren-ai-service/src/web/v1/services/question_recommendation.py
- wren-ai-service/src/web/v1/services/sql_answer.py
- wren-ai-service/src/web/v1/services/sql_expansion.py
- wren-ai-service/tests/pytest/pipelines/test_ask.py
- wren-ai-service/tests/pytest/services/mocks.py
- simplify pipeline dry run
- use formal version of AsyncDriver instead of experimental version
- unify configuration for apis
> chore(wren-ai-service): refactor

- wren-ai-service/src/web/v1/services/question_recommendation.py
This PR adds the `project_id` parameter to ensure proper project context is maintained during SQL generation.
- Ensures SQL generation is scoped to the correct project context
- Maintains data isolation between different projects
> fix(wren-ai-service): put the lacking project id for previewing data in the question recommendation

- wren-ai-service/src/pipelines/generation/question_recommendation.py
- wren-ai-service/src/pipelines/generation/semantics_description.py
- wren-ai-service/src/web/v1/services/__init__.py
- wren-ai-service/tests/pytest/services/test_relationship_recommendation.py
This PR updates the language parameter across multiple services to use ISO language codes instead of full language names, standardizing our localization approach.
- Changed default language from "English" to "en" across all services
- Updated prompt templates to clarify "Language" as "Localization Language"
- Modified language parameter in multiple pipeline classes:
- QuestionRecommendation
- SemanticsDescription
- Configuration model
> feat(wren-ai-service): prompt enhancement for localization language code and scoping the categories for questions generation

- wren-ui/src/apollo/server/config.ts
- wren-ui/src/apollo/server/services/askingService.ts
- wren-ui/src/apollo/server/services/projectService.ts
- wren-ui/src/components/pages/home/prompt/RecommendedQuestionsPrompt.tsx
- wren-ui/src/hooks/useRecommendedQuestionsInstruction.tsx
- wren-ui/src/pages/home/index.tsx
adjust recommend question to reduce cost 
- remove regenerate button
- reduce requested recommend question
> fix(wren-ui): adjust recommend question to reduce cost 

- wren-ai-service/src/pipelines/generation/question_recommendation.py
- Enhanced question recommendation pipeline to fully localize both questions and category names
```json
// Before
{
"question": "在 Wren AI Cloud 平台中，有多少用戶的電子郵件已經驗證？",
"category": "user_profile"
}
// After
{
"question": "在過去一年中，多少用戶的電子郵件已經驗證？",
"category": "用戶資料"
}
```
> feat(wren-ai-service): prompt enhancement to focus on localization language

- wren-ui/src/components/dataPreview/PreviewData.tsx
This feature allows users to easily copy the content of a table cell in the preview data view.
> feat(wren-ui): Support copy button in cell in preview data table

- wren-ai-service/src/pipelines/common.py
- wren-ai-service/src/pipelines/indexing/__init__.py
- wren-ai-service/src/pipelines/indexing/db_schema.py
- wren-ai-service/src/pipelines/indexing/historical_question.py
- wren-ai-service/src/pipelines/indexing/table_description.py
- wren-ai-service/tests/pytest/pipelines/indexing/test_db_schema.py
- wren-ai-service/tests/pytest/pipelines/indexing/test_indexing.py
1. **Document Cleaning Logic Refactoring**
- Moved document cleaning operation to after embedding generation to minimize the duration for empty document
2. **Async Implementation Updates**
- Added async support to `DDLChunker` methods
- Converted `_get_ddl_commands` and `_model_preprocessor` to async methods
- Implemented `asyncio.gather()` for parallel processing of model preprocessing
3. **Pipeline Flow Optimization**
- Updated pipeline steps order: validate → chunk → embed → clean → write
- Consistent implementation across all indexing pipelines (db_schema, historical_question, table_description)
4. **Logging Improvements**
- Added custom logger setup in `dry_run_pipeline`
> feat(wren-ai-service): minimize the duration for empty document and async helper for model preprocessor

- wren-ui/e2e/commonTests/home.ts
- wren-ui/src/apollo/client/graphql/__types__.ts
- wren-ui/src/apollo/client/graphql/home.generated.ts
- wren-ui/src/apollo/client/graphql/home.ts
- wren-ui/src/apollo/server/schema.ts
- wren-ui/src/components/pages/home/promptThread/AnswerResult.tsx
- wren-ui/src/components/pages/home/promptThread/BreakdownAnswer.tsx
- wren-ui/src/components/pages/home/promptThread/TextBasedAnswer.tsx
- wren-ui/src/components/pages/home/promptThread/ViewBlock.tsx
- wren-ui/src/components/pages/home/promptThread/index.tsx
- wren-ui/src/hooks/useAnswerStepContent.tsx
- wren-ui/src/hooks/useTextBasedAnswerStreamTask.tsx
- wren-ui/src/pages/home/[id].tsx
- wren-ui/src/utils/enum/home.ts
- wren-ui/src/utils/errorHandler.tsx
- Support Text to Answer UI
```bash
WREN_AI_SERVICE_VERSION=text2answer-streaming-v3
```
- Answer Result UI
- **Answer** tab
- The tab will be hidden for existing thread responses.
- Content
- status
- Start streaming data if threadResponse.answerDetail.status === `STREAMING` 
- Preview data
- Show a small string above the table
- `Considering the limit of context window, we only use {X} rows of results to generate the answer.`
- `numRowsUsedInLLM` **=== 0**
- Hide **View results** button and preview data table
- Do not call preview data API
- Handle error alert block
- Show regenerate answer button if the process is not completed (`INTERRUPTED` status)
- Show preview data when the last thread response (& `numRowsUsedInLLM` > 0)
- **View SQL** tab
- Move the original UI (breakdown answer) …
> feat(wren-ui): integrate API to support text-based answer

- wren-ui/Dockerfile
Context:
One community member reported that wren-ui docker image couldn't run in his environment(x86-64, Ubuntu, docker error code: 132). He solved the issue by changing the base image. Then we found that there are truly potential issues using alpine as base image. So, we change the base image from `alpine` to `bookworm-slim`. 
ref: https://snyk.io/blog/choosing-the-best-node-js-docker-image/
Result:
tested in local environment
original:
- image: ghcr.io/canner/wren-ui:0.18.0
- size: 184MB
new
- image: wrenai-wren-ui:latest
- size: 249MB
> chore(wren-ui): change alpine to bookworm-slim

- wren-ai-service/src/pipelines/generation/chart_adjustment.py
- wren-ai-service/src/pipelines/generation/chart_generation.py
- wren-ai-service/src/pipelines/generation/sql_answer.py
- wren-ai-service/src/pipelines/retrieval/retrieval.py
- text2chart:
- fix schema JSON decode issue
- text2answer:
- remove reasoning process
- remove technical jargon like SQL syntax
- refine prompt wording
> chore(wren-ai-service): improve text2chart and text2answer

- wren-ui/src/components/chart/handler.ts
> feat(wren-ui): Adjust x-axis label angle

- wren-ui/src/components/pages/home/promptThread/TextBasedAnswer.tsx
adjust text `Considering the limit of the context window, we retrieve up to 500 rows of results to generate the answer.`
> chore(wren-ui): adjust text-based answer view results remark

- wren-ai-service/src/pipelines/generation/question_recommendation.py
1. **Token Usage Optimization**
- Omitted MDL from prompt when previous questions exist
- Reduced token consumption by 69.56% (73.6K → 22.4K tokens)
- Decreased cost per request:
- GPT-4o-mini: $0.011 → $0.003
- GPT-40: $0.184 → $0.056
2. **Improved Question Relevance**
- Enhanced context awareness by focusing on question history
- Added structured guidelines for question generation
- Implemented randomized category selection for better diversity
> feat(wren-ai-service): Question Recommendation Pipeline Optimization

- .gitignore
- docker/README.md
- docker/docker-compose-dev.yaml
- docker/docker-compose.yaml
use `env_file` instead of letting users manually insert environment variables
help users add other custom env var such as other LLM api keys for litellm without manually changing docker compose yaml file
> chore(wren-ai-service): change docker compose yaml env var setup

- wren-launcher/commands/launch.go
- wren-launcher/go.mod
- wren-launcher/go.sum
- wren-launcher/utils/docker.go
- wren-launcher/utils/network.go
This PR simplifies how users use custom LLMs. Before, users need to manually type docker compose command to restart wren-ai-service. This PR makes the Wren AI launching process a lot easier:
1. fill in required information in .env and config.yaml
2. run launcher and choose Custom
This PR also fixes a Go security issue
> chore(wren-launcher): simplify launcher choosing custom

- deployment/kustomizations/base/cm.yaml
- docker/config.example.yaml
- wren-ai-service/src/web/v1/services/__init__.py
- wren-ai-service/tests/pytest/services/test_relationship_recommendation.py
- wren-ai-service/tools/config/config.example.yaml
- wren-ai-service/tools/config/config.full.yaml
- wren-launcher/utils/docker.go
According to OpenAI docs, in production applications, it is a best practice to use dated model snapshot IDs instead of aliases, which may change periodically.
ref: https://platform.openai.com/docs/models#current-model-aliases
> chore(wren-ai-service): make openai llm version fixed

- wren-ui/src/apollo/server/resolvers/modelResolver.ts
- wren-ui/src/apollo/server/utils/model.ts
- wren-ui/src/components/selectors/lineageSelector/index.tsx
- wren-ui/src/utils/columnType.tsx
- wren-ui/src/utils/enum/columnType.ts
- wren-ui/src/utils/validator/calculatedFieldValidator.ts
This PR addresses an issue where some calculated fields (CFs) fail to display in the model preview.
The engine requires all columns, including calculated fields, to be explicitly listed in the query when previewing a model. Using a wildcard (*) does not include calculated fields in the result.
Update the model preview query to explicitly list all columns and calculated fields, ensuring accurate previews. 
For example:
```
SELECT "col"..., "cf"... FROM "model"
```
- Add functionality to disable calculated fields in the same model
- Add some column types
> fix(wren-ui): Calculated fields in model preview Issue & improvements

- wren-ai-service/eval/__init__.py
- wren-ai-service/eval/evaluation.py
- wren-ai-service/eval/pipelines.py
- wren-ai-service/eval/preparation.py
- wren-ai-service/eval/utils.py
This PR introduces instruction handling capabilities to the evaluation framework with three main changes:
1. Added instructions field to evaluation dataset preparation:
- Extracts evidence as instructions from ground truth data
- Restructures SQL pairs format for better clarity
- Maintains backward compatibility with existing dataset structure
2. Enhanced prediction parameters to include instructions:
- Added instructions field to prediction parameter set
- Modified SQL pairs format to separate question and SQL components
3. Added configuration flags for feature control:
- Introduced `allow_instructions` flag alongside existing `allow_sql_samples`
- Enables granular control over which features are active during evaluation
Related PR: https://github.com/Canner/WrenAI/pull/1376
> feat(wren-ai-service): Add Instructions Support to Evaluation Dataset and Prediction Parameters

- wren-ui/src/components/pages/home/promptThread/AnswerResult.tsx
- Use rephrasedQuestion first
- For asking a question/follow-up question, will use 'rephrasedQuestion' as the initial value for the question of the Add Question-SQL pair Modal
- For clicking a Recommended question in a thread page, will use ‘question’ as the initial value for the question of the Add Question-SQL pair Modal
> feat(wren-ui): Use rephrasedQuestion for asking a question answer

- wren-ui/src/apollo/server/adaptors/wrenAIAdaptor.ts
correct generate instruction request payload:
- `project_id` should be at the first layer
> fix(wren-ui): correct generate instruction request payload

- wren-ui/src/components/editor/MarkdownBlock.tsx
- wren-ui/src/components/editor/MarkdownEditor.tsx
- wren-ui/src/components/modals/AdjustReasoningStepsModal.tsx
- wren-ui/src/components/pages/home/promptThread/BreakdownAnswer.tsx
- wren-ui/src/components/pages/home/promptThread/ChartAnswer.tsx
- wren-ui/src/components/pages/home/promptThread/TextBasedAnswer.tsx
- wren-ui/src/components/pages/home/promptThread/store.tsx
- wren-ui/src/hooks/useMentions.tsx
- wren-ui/src/pages/home/[id].tsx
- wren-ui/src/utils/error/dictionary.ts
- Add adjust reasoning modal
- Add markdown editor
- Add mentions feature
- Refine styles of adjust answer
- Edit mode
- Read mode 
- Select models 
- Mentions 
- Error
> feat(wren-ui): Add adjust reasoning steps model with Markdown editor

- wren-ui/src/apollo/client/graphql/home.generated.ts
- wren-ui/src/apollo/client/graphql/home.ts
- wren-ui/src/components/modals/AdjustSQLModal.tsx
- wren-ui/src/components/pages/home/promptThread/AnswerResult.tsx
- wren-ui/src/components/pages/home/promptThread/TextBasedAnswer.tsx
- wren-ui/src/components/pages/home/promptThread/ViewSQLTabContent.tsx
- wren-ui/src/components/pages/home/promptThread/store.tsx
- wren-ui/src/hooks/useAdjustAnswer.tsx
- wren-ui/src/pages/home/[id].tsx
- wren-ui/src/utils/errorHandler.tsx
This pull request includes several changes to the `wren-ui` project, primarily focused on adding support for SQL adjustments and removing the breakdown answer generation functionality. The most important changes include updating the `AdjustSQLModal` component to handle `responseId`, modifying the `AnswerResult` component to display adjustment information, and updating the `useAdjustAnswer` hook to fetch thread responses after SQL adjustments.
- Integrate adjust thread response SQL API
- Remove breakdown answer generation
> feat(wren-ui): Integrate adjust SQL API

- wren-ui/package.json
- wren-ui/yarn.lock
upgrade tar-fs to 2.1.3
fix security dependency: https://github.com/Canner/WrenAI/security/dependabot/82
> chore(wren-ui): upgrade tar-fs to 2.1.3
