Canner/WrenAI

.github/workflows/ai-service-release-stable-image.yaml

This PR resolved the issue #71. we created a GitHub APP in the organization and permitted it to bypass required pull requests when merging and pushing onto the protected branch.
- [Registering a GitHub App](https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/registering-a-github-app#registering-a-github-app)
- [Installing your own GitHub App](https://docs.github.com/en/apps/using-github-apps/installing-your-own-github-app#installing-your-own-github-app)
- [Authenticate in Actions workflow](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/making-authenticated-api-requests-with-a-github-app-in-a-github-actions-workflow)
- [Require pull request reviews before merging](https://docs.github.com/en/repositories/configuring-branches-an …

feature(ai-service): push on protected branch that required PR before merging via GitHub APP as the bot

---

wren-ai-service/pyproject.toml

add aster in the list of authors in pyproject.toml

add aster as author

---

wren-ai-service/src/eval/ask/streamlit_app.py

Update ask evaluation streamlit path of outputs folder

update ask evaluation outputs path in streamlit app

---

wren-ai-service/src/eval/ask_details/__main__.py
wren-ai-service/src/eval/ask_details/utils.py
wren-ai-service/src/pipelines/ask_details/components/post_processors.py
wren-ai-service/src/pipelines/ask_details/generation_pipeline.py

in #86, we mentioned the breaking changes for the ask details evaluation process. and fixed them here. 😃

fix(ai-service): correct the breaking change for ask details evaluation process

---

wren-ui/src/apollo/server/mdl/mdlBuilder.ts
wren-ui/src/apollo/server/mdl/test/mdlBuilder.test.ts
wren-ui/src/apollo/server/mdl/type.ts
wren-ui/src/apollo/server/resolvers.ts
wren-ui/src/apollo/server/resolvers/diagramResolver.ts
wren-ui/src/apollo/server/resolvers/modelResolver.ts
wren-ui/src/apollo/server/resolvers/projectResolver.ts
wren-ui/src/apollo/server/schema.ts
wren-ui/src/apollo/server/services/mdlService.ts
wren-ui/src/apollo/server/types/context.ts
wren-ui/src/apollo/server/types/diagram.ts
wren-ui/src/pages/api/graphql.ts

* Add view create/delete API
* Add view validation API
* Add view preview data API
* Add views field to diagram API

feat(wren-ui): Add views create/delete, validation, preview data APIs

---

.github/workflows/ui-lint.yaml
.github/workflows/ui-test.yaml

Prevent ai service from running ui workflow

Chore: Prevent ai service from running ui workflow

---

wren-ui/src/apollo/server/factories/onboardingFactory.ts
wren-ui/src/apollo/server/mdl/test/mdlBuilder.test.ts

Change the project catalog & schema to wrenai.public

Fix(wren-ui): change project schema & catalog to wrenai

---

wren-ui/src/components/diagram/CustomDropdown.tsx
wren-ui/src/components/diagram/customNode/ViewNode.tsx

- handle view fields more than config.limit length (50)
- more icon - visible dropdown menu

chore(wren-ui): Enhance view node

---

wren-ui/src/apollo/client/graphql/__types__.ts
wren-ui/src/components/pages/setup/Starter.tsx
wren-ui/src/components/pages/setup/dataSources/BigQueryProperties.tsx
wren-ui/src/components/pages/setup/dataSources/PostgreSQLProperties.tsx
wren-ui/src/components/pages/setup/utils.tsx
wren-ui/src/utils/enum/dataSources.ts
wren-ui/src/utils/error/dictionary.ts

- Add PostgreSQL UI on onboarding
- BigQuery - https://docs.getwren.ai/guide/connect/bigquery
- DuckDB - https://docs.getwren.ai/guide/connect/duckdb
- PostgreSQL - https://docs.getwren.ai/guide/connect/postgresql

feat(wren-ui): Add PostgreSQL UI for onboarding

---

wren-ui/src/components/pages/setup/utils.tsx

Remove the music store sample dataset

chore(wren-ui): Remove music store sample dataset

---

wren-ui/src/apollo/server/data/sample.ts

Fix lint issue in sample dataset

fix(wren-ui): fix lint in sample dataset

---

wren-launcher/utils/docker.go

Release 0.2.0-rc.1

---

wren-launcher/commands/launch.go

Do you agree to help us by sending anonymous usage data? (yes/no, default is y) -> Do you agree to help us by sending anonymous usage data? (y/n, default is y)

fix wording in launcher

---

wren-ui/src/apollo/server/adaptors/wrenEngineAdaptor.ts
wren-ui/src/apollo/server/utils/error.ts

Provide better error message when using duckdb as the datasource

Fix(wren-ui): provide better error message

---

wren-ui/src/components/pages/setup/ConnectDataSource.tsx
wren-ui/src/components/pages/setup/SelectModels.tsx
wren-ui/src/hooks/useCheckOnboarding.tsx
wren-ui/src/hooks/useCombineFieldOptions.tsx

- Allow back to previous steps for onboarding
- Should get the latest API data since source data may be changed
- UI improve
- Allow back to previous steps for onboarding
- Fix typo
- Update doc link
- Update fetch policy to get models list

fix(wren-ui): allow back to previous steps for onboarding and improve

---

wren-launcher/utils/docker.go

Release 0.2.0-rc.2

---

wren-ai-service/demo/sample_dataset/nba_duckdb_mdl.json
wren-ai-service/src/utils.py
wren-ui/src/apollo/server/data/sample.ts

- fix nba dataset column names that start with number

fix nba dataset

---

wren-launcher/utils/docker.go

release 0.2.1-rc.1

---

wren-ui/src/apollo/server/data/sample.ts
wren-ui/src/apollo/server/resolvers/projectResolver.ts
wren-ui/src/apollo/server/services/modelService.ts

allow setting model/column properties on demo dataset

Chore: update sample dataset model/column properties

---

wren-ui/migrations/20240419090560_update_relationship_table.js
wren-ui/src/apollo/server/factories/bqStrategy.ts
wren-ui/src/apollo/server/factories/dataSourceStrategy.ts
wren-ui/src/apollo/server/factories/duckdbStrategy.ts
wren-ui/src/apollo/server/factories/postgresStrategy.ts
wren-ui/src/apollo/server/factories/util.ts
wren-ui/src/apollo/server/models/model.ts
wren-ui/src/apollo/server/repositories/modelColumnRepository.ts
wren-ui/src/apollo/server/resolvers.ts
wren-ui/src/apollo/server/resolvers/modelResolver.ts
wren-ui/src/apollo/server/schema.ts

Feature: Implement Model mutation

---

wren-ui/src/components/pages/modeling/form/ModelForm.tsx
wren-ui/src/utils/error/dictionary.ts

- Update the validator since the primary key is not the required field
- Allow a user to clear the primary key value

fix(wren-ui): update primary key validator for model form

---

wren-ui/src/components/EditableWrapper.tsx
wren-ui/src/components/pages/modeling/EditMetadataModal.tsx
wren-ui/src/components/pages/modeling/MetadataDrawer.tsx
wren-ui/src/components/pages/modeling/metadata/EditBasicMetadata.tsx
wren-ui/src/components/pages/modeling/metadata/EditModelMetadata.tsx
wren-ui/src/components/pages/modeling/metadata/ModelMetadata.tsx
wren-ui/src/components/table/BaseTable.tsx
wren-ui/src/components/table/EditableBaseTable.tsx
wren-ui/src/components/table/FieldTable.tsx
wren-ui/src/components/table/RelationTable.tsx
wren-ui/src/pages/modeling.tsx

- Support Edit Model Metadata UI
- Adjust update metadata flow

feat(wren-ui): Support edit Model metadata UI

---

wren-ui/migrations/20240502000000_add_properties_to_relationship.js
wren-ui/src/apollo/server/mdl/mdlBuilder.ts
wren-ui/src/apollo/server/mdl/test/mdlBuilder.test.ts
wren-ui/src/apollo/server/mdl/type.ts
wren-ui/src/apollo/server/models/model.ts
wren-ui/src/apollo/server/repositories/relationshipRepository.ts
wren-ui/src/apollo/server/resolvers.ts
wren-ui/src/apollo/server/resolvers/diagramResolver.ts
wren-ui/src/apollo/server/resolvers/modelResolver.ts
wren-ui/src/apollo/server/schema.ts
wren-ui/src/apollo/server/types/diagram.ts

* Support update model metadata API: `updateModelMetadata` mutation
* Add description field to relationship in `Diagram` query
* If users give empty string, backend will set the field to null in database
* Adding `description` to model, column properties
* Adding `properties` to relationship, which will include description.
<details>
<summary>MDL</summary>
```js
{
"schema": "public",
"catalog": "wrenai",
"models": [
{
"name": "customers",
"columns": [
{
"name": "City",
"type": "VARCHAR",
"isCalculated": 0,
"notNull": 0,
"expression": "",
"properties": {
"description": "The Customer City, where the customer company is located. Also called \"customer segment\".",
"displayName": "City"
}
},
{
"name": "Id",
"type": "VARCHAR",
"isCalculated": 0,
"notNull": 0,
"expression": "",
"properties": { …
```

Feature: support update model metadata API

---

wren-ui/src/apollo/server/resolvers/diagramResolver.ts

Fix parsing of relation properties in diagramResolver.ts

Fix parsing of relation properties in diagramResolver.ts

---

wren-ui/src/apollo/server/repositories/modelRepository.ts
wren-ui/src/apollo/server/repositories/relationshipRepository.ts
wren-ui/src/apollo/server/resolvers.ts
wren-ui/src/apollo/server/resolvers/modelResolver.ts
wren-ui/src/apollo/server/schema.ts
wren-ui/src/apollo/server/services/modelService.ts
wren-ui/src/apollo/server/types/relationship.ts

support relation CRUD operation

Feature: support relation CRUD operation

---

wren-ui/src/apollo/client/graphql/__types__.ts
wren-ui/src/apollo/client/graphql/diagram.generated.ts
wren-ui/src/apollo/client/graphql/diagram.ts
wren-ui/src/apollo/client/graphql/metadata.generated.ts
wren-ui/src/apollo/client/graphql/metadata.ts
wren-ui/src/apollo/server/resolvers/diagramResolver.ts
wren-ui/src/components/pages/modeling/EditMetadataModal.tsx
wren-ui/src/components/pages/modeling/MetadataDrawer.tsx
wren-ui/src/components/pages/modeling/metadata/EditModelMetadata.tsx
wren-ui/src/hooks/useDrawerAction.tsx
wren-ui/src/pages/modeling.tsx
wren-ui/src/utils/errorHandler.tsx

- Integrating Update Model Metadata to edit metadata

feat(wren-ui): UI integrating API to model metadata

---

wren-ui/src/components/modals/CalculatedFieldModal.tsx

Add primary key doc link in calculated field modal

chore(wren-ui): add primary key doc link

---

wren-mdl/mdl.schema.json

Fix the syntax of JSON schema.
I have tried this schema by the online [ajv validation](https://npm.runkit.com/ajv) by the followed sample code
```js
const Ajv2020 = require("ajv/dist/2020")
const ajv = new Ajv2020()
const schema = {
// the json schema 
}
const validate = ajv.compile(schema)
test({catalog: "test", schema: "test"})
test({catalog: "test", schema: "test"})
function test(data) {
const valid = validate(data)
if (valid) console.log("Valid!")
else console.log("Invalid: " + ajv.errorsText(validate.errors))
}
```

Fix(MDL) Fix the JSON schema of MDL

---

wren-ui/src/components/diagram/Marker.tsx

The SVG embed definitions have affected user operation.

fix(wren-ui): Fix svg embed definitions styles that affected user operation

---

wren-ui/src/apollo/server/data/sample.ts

Fix(Wren-ui): add demo dataset table descriptions

---

wren-ai-service/src/pipelines/ask/followup_generation_pipeline.py
wren-ai-service/src/pipelines/ask/generation_pipeline.py
wren-ai-service/src/pipelines/ask/indexing_pipeline.py
wren-ai-service/src/pipelines/ask/query_understanding_pipeline.py
wren-ai-service/src/pipelines/ask/retrieval_pipeline.py
wren-ai-service/src/pipelines/ask/sql_correction_pipeline.py
wren-ai-service/src/pipelines/ask_details/generation_pipeline.py
wren-ai-service/src/web/v1/services/ask.py

add logger using info level and fix indexing status

add logger using info level and fix indexing status

---

wren-ai-service/src/__main__.py
wren-ai-service/src/web/v1/routers.py
wren-ai-service/src/web/v1/services/ask.py
wren-ai-service/src/web/v1/services/ask_details.py

- fixing inconsistent api status issues for ask, ask details and prepare_semantics apis
- health check api: /health

api refactor and add healthcheck api

---

wren-ui/src/apollo/server/connectors/postgresConnector.ts
wren-ui/src/apollo/server/connectors/types.ts
wren-ui/src/apollo/server/tests/connector.test.ts

Fix that postgres connector return native data types instead of types we defined in enum

fix(wren-ui): in pg connector, we return column types in enum

---

wren-launcher/utils/docker.go

release 0.3.0-rc.2

---

wren-launcher/utils/docker.go

release 0.3.1

---

wren-ui/src/components/pages/modeling/form/ModelForm.tsx

- Allow column case insensitive search for column selector

feat(wren-ui): allow column case insensitive search for column selector

---

wren-launcher/commands/launch.go
wren-launcher/utils/docker.go

can see health check from log
docker-compose : https://gist.githubusercontent.com/onlyjackfrost/e5c170d70fce27bb24272601e313a9da/raw/fc0e16f251e84527398bf7e7c04ab2cc0ee96f25/docker-compose.yaml
env example: https://gist.githubusercontent.com/onlyjackfrost/6a2561f08fcc6b4e6eea31973542e40d/raw/343c6a225d54c74965c9014197fc0e957b6759d1/.env.example

Chore(wren-ui): wait ai service ready before open browser

---

wren-ui/src/components/HeaderBar.tsx

Remove share button first until pg ready for sharing

chore(wren-ui): Remove share button on Modeling

---

wren-ai-service/src/pipelines/ask/indexing_pipeline.py
wren-ai-service/src/web/v1/services/ask.py
wren-ai-service/src/web/v1/services/ask_details.py

- added logger.error to dump error messages to terminal in each ai pipeline for every failed case
- fixed view indexing issue

add logger.error messages

---

wren-ui/src/apollo/server/services/modelService.ts
wren-ui/src/apollo/server/utils/error.ts
wren-ui/src/components/ErrorCollapse.tsx
wren-ui/src/components/modals/CalculatedFieldModal.tsx
wren-ui/src/components/pages/home/prompt/Result.tsx
wren-ui/src/pages/modeling.tsx
wren-ui/src/utils/errorHandler.tsx

We need to provide wren-engine error message when the user is creating or updating the calculated field.
At least to know the error message for debugging.
- collapse

feat(wren-ui): Backend API provide error message from wren engine

---

wren-ai-service/src/pipelines/ask/indexing_pipeline.py

fix view indexing if "view" is not included in mdl files

Chore/ai service/fix indexing

---

wren-launcher/utils/docker.go

release 0.3.2-rc.1

---

wren-launcher/utils/docker.go

release 0.3.2-rc.2

---

wren-ai-service/src/pipelines/ask/indexing_pipeline.py

- fix view indexing issue
- add ddl store indexing description

fix indexing bug

---

wren-launcher/utils/docker.go

release 0.3.2-rc.3

---

wren-ui/src/pages/_app.tsx
wren-ui/src/utils/env.ts

Add tracking page view when router changing

chore(wren-ui): Tracking page view when router change

---

docker/docker-compose.yaml
wren-launcher/utils/docker.go
wren-ui/src/apollo/server/config.ts
wren-ui/src/apollo/server/telemetry/telemetry.ts

- add `openaiGenerationModel` to posthog's telemetry

Chore(wren-ui): record openai generation model used by user

---

wren-launcher/commands/launch.go
wren-launcher/config/config.go
wren-launcher/main.go
wren-launcher/utils/docker.go

- can use disable-telemetry to optout
- without option

Chore: provide opt-out option in CLI argument

---

wren-launcher/utils/docker.go

release 0.3.3-rc.1

---

wren-ui/src/apollo/server/adaptors/wrenAIAdaptor.ts
wren-ui/src/components/deploy/Deploy.tsx

Show deploying error toast, and remind the user to check the detail in logs.

chore(wren-ui): Show AI exception errors to client when deploying manifest

---

wren-ai-service/src/pipelines/ask/indexing_pipeline.py

chore: update indexing_pipeline.py

---

docker/bootstrap/init.sh

Enable dynamic-fields config for Wren Engine

feature(wren-launcher): enable dynamic-fields config for Wren Engine

---

LICENSE

Update templated sections in license

Update templated sections in license

---

docker/bootstrap/init.sh

fix adding properties to config.properties

fix(wren-launcher): fix adding properties to config.properties

---

wren-ui/src/apollo/server/resolvers/modelResolver.ts

fix(wren-ui/api): fix update model metadata API

---

wren-ai-service/README.md

- add concepts section
- fix eval instructions

refine readme

---

wren-ui/src/apollo/server/factories/bqStrategy.ts
wren-ui/src/apollo/server/factories/duckdbStrategy.ts
wren-ui/src/apollo/server/factories/postgresStrategy.ts

fix issue #181 
Can create the model and deploy successfully

Fix: Improve batch processing for creating model columns

---

wren-ui/src/apollo/server/connectors/bqConnector.ts
wren-ui/src/apollo/server/connectors/duckdbConnector.ts
wren-ui/src/apollo/server/connectors/postgresConnector.ts
wren-ui/src/apollo/server/factories/postgresStrategy.ts
wren-ui/src/apollo/server/utils/error.ts
wren-ui/src/components/pages/setup/ConnectDataSource.tsx
wren-ui/src/components/pages/setup/utils.tsx
wren-ui/src/components/settings/DataSourceSettings.tsx
wren-ui/src/hooks/useSetupConnection.tsx
wren-ui/src/pages/setup/connection.tsx
wren-ui/src/utils/errorHandler.tsx

Improving data source connection error messages helps users quickly understand and resolve issues.
- Provide `CONNECTION_ERROR` & `CONNECTION_REFUSED` error to client
- Refine UI in error alert component
- Provide instruction link when PG connection refused
Connection Error
Connection Refused in PG

chore(wren-ui): Enhance data source connection error & instructions

---

wren-ui/src/apollo/server/connectors/postgresConnector.ts
wren-ui/src/apollo/server/factories/postgresStrategy.ts

- Setup `rejectUnauthorized` for ssl connection
- Add `sslmode=require` to jdbc url
close #296

fix(wren-ui): Setup rejectUnauthorized for ssl connection & add sslmode to jdbc url

---

wren-ui/README.md
wren-ui/migrations/20240524044348_update_project_table.js
wren-ui/migrations/20240524071859_update_thread_table.js
wren-ui/src/apollo/server/config.ts
wren-ui/src/apollo/server/repositories/projectRepository.ts
wren-ui/src/apollo/server/repositories/threadResponseRepository.ts

Fix schema issue to use PG & SQLite as our database.
Set sqlite as our default database.
To use PG as database
```
export DB_TYPE=pg
```

Fix(wren-ui): use postgres as database

---

wren-ui/src/apollo/client/graphql/__types__.ts
wren-ui/src/apollo/client/graphql/home.generated.ts
wren-ui/src/apollo/client/graphql/home.ts
wren-ui/src/apollo/server/resolvers/askingResolver.ts
wren-ui/src/apollo/server/schema.ts
wren-ui/src/components/pages/home/prompt/Result.tsx
wren-ui/src/components/pages/home/promptThread/AnswerResult.tsx

present view displayName instead of name in home page

Fix(wren-ui): present view displayName instead of name in home page 

---

wren-ai-service/pyproject.toml
wren-ai-service/src/web/v1/services/ask.py
wren-ai-service/tests/locust/locust.conf
wren-ai-service/tests/locust/locust_script.py
wren-ai-service/tests/locust/locustfile.py

- Move locust config to tests/locust/locust.conf
- Adjust test case waiting
- Remove timer from ask service

Chore(wren-ai-service): adjust locust test

---

wren-ui/src/apollo/server/adaptors/wrenEngineAdaptor.ts

Fix(wren-ui): fix lint after upgrade axios

---

wren-ai-service/poetry.lock
wren-ai-service/pyproject.toml
wren-ai-service/src/engine.py
wren-ai-service/src/pipelines/ask/components/post_processors.py
wren-ai-service/src/pipelines/ask/followup_generation.py
wren-ai-service/src/pipelines/ask/generation.py
wren-ai-service/src/pipelines/ask/historical_question.py
wren-ai-service/src/pipelines/ask/retrieval.py
wren-ai-service/src/pipelines/ask/sql_correction.py
wren-ai-service/src/pipelines/ask_details/generation.py
wren-ai-service/src/providers/document_store/qdrant.py
wren-ai-service/src/utils.py
wren-ai-service/src/web/v1/services/ask.py

This PR aims to make the SQL dry-run and Qdrant components support async tasks. and also extract the function related to the engine to a module.
- https://python-client.qdrant.tech/qdrant_client.async_qdrant_client
- https://docs.aiohttp.org/en/stable/client_quickstart.html#make-a-request

feature(wren-ai-service): support async SQL dry-run and async Qdrant component 

---

wren-ui/src/apollo/server/resolvers/askingResolver.ts

fix sql not show after clicking "View Full SQL" button

Fix: fix sql not show after clicking "View Full SQL" button

---

wren-ui/src/apollo/client/graphql/__types__.ts
wren-ui/src/apollo/client/graphql/view.generated.ts
wren-ui/src/apollo/client/graphql/view.ts
wren-ui/src/apollo/server/resolvers/askingResolver.ts
wren-ui/src/apollo/server/resolvers/modelResolver.ts
wren-ui/src/apollo/server/schema.ts
wren-ui/src/apollo/server/services/askingService.ts

- Add limit property for preview data
- Fix all view related APIs that need to provide displayName in the `ViewInfo` type

feat(wren-ui): Provide limit property in preview data API for excel-add-in used

---

wren-ui/src/apollo/server/repositories/baseRepository.ts

Use batch create in createMany method
all repository use createMany

Fix(wren-ui): createMany with too many input value issue

---

wren-ai-service/src/web/v1/services/ask.py

return at most 1 candidate result that is saved from view

fix saved as view number

---

wren-ai-service/src/pipelines/ask/historical_question.py

make filter score threshold 0.8

fix filter score issue

---

wren-ui/src/apollo/server/adaptors/ibisAdaptor.ts
wren-ui/src/apollo/server/adaptors/tests/ibisAdaptor.test.ts
wren-ui/src/apollo/server/repositories/projectRepository.ts
wren-ui/src/apollo/server/resolvers/modelResolver.ts
wren-ui/src/apollo/server/resolvers/projectResolver.ts
wren-ui/src/apollo/server/schema.ts
wren-ui/src/apollo/server/services/metadataService.ts
wren-ui/src/apollo/server/services/projectService.ts
wren-ui/src/apollo/server/services/queryService.ts
wren-ui/src/apollo/server/types/dataSource.ts

- Support MySQL data source and refactor codebase
- Fix connect to PostgreSQL with SSL issue #417 
- Can create view and calculated field with MySQL data source
- Can preview data with Model

Feature(wren-ui): Support MySQL data source

---

wren-ui/src/apollo/server/resolvers.ts
wren-ui/src/apollo/server/resolvers/modelResolver.ts
wren-ui/src/apollo/server/schema.ts

Change getMDL API from mutation to query and adjust input variable
(POST)/api/graphql
```json
{
"query": "query GetMDL($hash: String!) { getMDL(hash: $hash){ hash mdl} }",
"variables":{
"hash": "test"   
}
}
```

Chore(wren-ui): update getMDL API 

---

.github/ISSUE_TEMPLATE/bug_report.md

add collecting log instruction in bug report template

Chore: add collecting log instruction in bug report template

---

.github/ISSUE_TEMPLATE/bug_report.md
LICENSE
README.md
deployment/kustomizations/README.md
wren-ai-service/README.md
wren-ai-service/demo/app.py
wren-launcher/commands/launch.go
wren-launcher/utils/docker.go
wren-ui/e2e/README.md
wren-ui/src/apollo/server/adaptors/wrenAIAdaptor.ts
wren-ui/src/components/LogoBar.tsx
wren-ui/src/components/settings/index.tsx
wren-ui/src/pages/_app.tsx

Rename wren ai

---

wren-launcher/Makefile
wren-ui/src/apollo/server/resolvers/modelResolver.ts
wren-ui/src/apollo/server/schema.ts
wren-ui/src/apollo/server/services/deployService.ts

- support force deploy
- update launcher makefile

Chore: support force deploy

---

docker/README.md
docker/docker-compose.llm.yaml
docker/docker-compose.yaml
wren-launcher/commands/launch.go
wren-launcher/utils/docker.go

- override compose file if using custom llm
- rm prior design legecy in launcher

Chore: override compose file if using custom llm

---

wren-launcher/utils/docker.go

Chore: add comment 

---

wren-ui/src/apollo/server/managers/dataSourceSchemaDetector.ts
wren-ui/src/apollo/server/resolvers/projectResolver.ts

Improve schema change source code.
- getAffectedResources as a reuse function
- Improve function and reduce duplicate code

chore(wren-ui): Improve schema change

---

wren-ui/src/apollo/server/resolvers/modelResolver.ts
wren-ui/src/apollo/server/resolvers/projectResolver.ts

Add a quote to the SQL table name in PreviewModelData API.
related issue: #474

fix(wren-ui): Add quote to SQL in preview model data API

---

wren-ai-service/src/web/v1/services/ask_details.py
wren-ai-service/tests/pytest/services/test_ask_details.py

fix https://github.com/Canner/WrenAI/issues/474

add quotes for the fallback option when sql breakdown fails

---

wren-ui/src/apollo/server/adaptors/ibisAdaptor.ts
wren-ui/src/apollo/server/adaptors/wrenEngineAdaptor.ts
wren-ui/src/apollo/server/data/sample.ts
wren-ui/src/apollo/server/resolvers/modelResolver.ts
wren-ui/src/apollo/server/schema.ts
wren-ui/src/apollo/server/services/askingService.ts
wren-ui/src/apollo/server/services/deployService.ts
wren-ui/src/apollo/server/services/queryService.ts
wren-ui/src/apollo/server/services/tests/deployService.test.ts
wren-ui/src/pages/api/graphql.ts

Some code changes to reflect the adjustment of Wren Engine v0.6.0
- don’t need to deploy Wren Engine anymore
- need to attach MDL doing preview/validate/analysis
- add limit options in query API

Chore: some update to reflect the adjustment of Wren Engine v0.6.0

---

wren-ai-service/src/providers/embedder/azure_openai.py
wren-ai-service/src/utils.py

- update azure_openai embedder
- explicitly pass public_key, secret_key and host to `langfuse_context.configure` and add logging info

Chore/ai service/minor update

---

wren-ai-service/entrypoint.sh
wren-ai-service/src/force_deploy.py

- fix trigger method of `force_deploy.py` in `entrypoint.sh`

fix trigger method for `foce_deploy.py`

---

wren-ui/src/apollo/server/adaptors/tests/ibisAdaptor.test.ts
wren-ui/src/apollo/server/services/modelService.ts
wren-ui/src/apollo/server/utils/helper.ts
wren-ui/src/apollo/server/utils/index.ts
wren-ui/src/utils/helper.ts

fix import error and add some test cases for ibis server

Fix(wren-ui): fix unit test and add some test cases for ibis adapter

---

wren-ui/migrations/20240711021133_create_thread_response_explain_table.js
wren-ui/migrations/20240711082655_update_thread_response_table.js
wren-ui/src/apollo/server/adaptors/wrenAIAdaptor.ts
wren-ui/src/apollo/server/adaptors/wrenEngineAdaptor.ts

Add migration files
Update adaptors

Chore: add migration files and update adaptors for feedback loop feature

---

wren-ui/src/apollo/server/backgroundTrackers/index.ts
wren-ui/src/apollo/server/backgroundTrackers/threadResponseBackgroundTracker.ts
wren-ui/src/apollo/server/services/askingService.ts

move background tracker for thread responses

Chore: move background tracker for thread responses

---

wren-ui/src/apollo/server/adaptors/ibisAdaptor.ts
wren-ui/src/apollo/server/adaptors/wrenEngineAdaptor.ts
wren-ui/src/apollo/server/resolvers/projectResolver.ts
wren-ui/src/apollo/server/services/deployService.ts
wren-ui/src/apollo/server/services/projectService.ts

Chore: remove logs 

---

.github/ISSUE_TEMPLATE/bug_report.md

Chore: rm instruction

---

.gitmodules

Hi everyone,
Would you mind adding a submodule for [Wren Engine](https://github.com/Canner/wren-engine)? It's a really great project that I think you will find beneficial.

Add wren engine as a submodule

---

CONTRIBUTING.md

DOCS: add wren-ui description

---

wren-ai-service/eval/data_curation/app.py
wren-ai-service/eval/data_curation/utils.py
wren-ai-service/eval/utils.py
wren-ai-service/tests/pytest/eval/test_column.py

- fix contexts
- add documents based on contexts

chore(wren-ai-service): eval data curation app updates

---

wren-ai-service/poetry.lock
wren-ai-service/pyproject.toml
wren-ai-service/src/__main__.py
wren-ai-service/src/core/engine.py
wren-ai-service/src/core/provider.py
wren-ai-service/src/globals.py
wren-ai-service/src/pipelines/ask/components/post_processors.py
wren-ai-service/src/pipelines/ask/followup_generation.py
wren-ai-service/src/pipelines/ask/generation.py
wren-ai-service/src/pipelines/ask/sql_correction.py
wren-ai-service/src/pipelines/ask_details/generation.py
wren-ai-service/src/pipelines/common.py
wren-ai-service/src/pipelines/sql_regeneration/generation.py
wren-ai-service/src/providers/engine/wren.py
wren-ai-service/src/providers/llm/azure_openai.py
wren-ai-service/src/providers/llm/ollama.py
wren-ai-service/src/providers/llm/openai.py
wren-ai-service/src/utils.py
wren-ai-service/src/web/v1/routers.py
wren-ai-service/src/web/v1/services/ask.py
wren-ai-service/src/web/v1/services/ask_details.py
wren-ai-service/src/web/v1/services/indexing.py
wren-ai-service/src/web/v1/services/sql_explanation.py
wren-ai-service/src/web/v1/services/sql_regeneration.py
wren-ai-service/tests/data/mock_pyproject.toml
wren-ai-service/tests/pytest/services/test_ask.py
wren-ai-service/tests/pytest/test_utils.py

This PR enhances Langfuse tracing by adding metadata, including the generation model, embedding model, service version, request model deployment ID, project ID, and thread ID. It ensures that all metadata is collected and flushed to Langfuse before the service shuts down, preventing any data loss.
I believe enabling Langfuse does not impact performance. The following tables estimate the time cost of handling three questions in both enabled and disabled states.
| Langfuse Status | Round  | AskService.ask Elapsed Time | AskDetailsService.ask_details Elapsed Time |
|-----------------|--------|-----------------------------|--------------------------------------------|
| Enable          | Round 1 | 10.5156 seconds             | 6.5332 seconds                             |
| Enable          | …

feat(wren-ai-service): add metadata into Langfuse trace

---

wren-ai-service/src/providers/engine/wren.py

add limit 1 to all variants of engine

chore(wren-ai-service): update dry run api parameter

---

wren-ai-service/.env.dev.example
wren-ai-service/src/utils.py
wren-ai-service/src/web/v1/services/ask.py
wren-ai-service/src/web/v1/services/ask_details.py
wren-ai-service/src/web/v1/services/indexing.py

- refine langfuse metadata and output

chore(wren-ai-service): refine langfuse

---

wren-ai-service/eval/.env.example
wren-ai-service/eval/README.md
wren-ai-service/eval/evaluation.py
wren-ai-service/eval/metrics/column.py
wren-ai-service/eval/pipelines.py
wren-ai-service/eval/prediction.py

This PR introduces a question-based accuracy metric, where the overall accuracy for a question is set to 1 if any candidate's score is 1. It also fixes the contextual precision metric to ensure scores do not exceed 1 and adds faithfulness to the generation metrics. Additionally, a batch mechanism is implemented to reduce frequent requests to the engine, which helps prevent errors.

feat(wren-ai-service): question based accuracy metric

---

.gitignore
wren-ai-service/eval/preparation.py

add a script under the eval folder for mdl properties preparation
- generating csv file that is easier for non-technical users to update mdl properties
- filling in mdl properties defined in csv file to mdl json file

chore(wren-ai-service): add script for mdl properties preparation

---

wren-ai-service/demo/utils.py
wren-ai-service/eval/data_curation/utils.py
wren-ai-service/eval/utils.py
wren-ai-service/src/core/engine.py
wren-ai-service/src/pipelines/ask/components/post_processors.py
wren-ai-service/src/pipelines/common.py
wren-ai-service/src/providers/engine/wren.py
wren-ai-service/src/web/v1/services/ask.py
wren-ai-service/src/web/v1/services/ask_details.py

sometimes generated sql may break sqlglot's transpile method, this PR fixes this issue

chore(wren-ai-service): handle add_quotes error

---

wren-ai-service/src/pipelines/ask/historical_question.py
wren-ai-service/src/pipelines/ask/retrieval.py
wren-ai-service/src/web/v1/services/ask.py

add project id to historical question pipeline

chore(wren-ai-service): fix historical question pipeline

---

deployment/kustomizations/helm-values-qdrant_1.11.0.yaml
deployment/kustomizations/kustomization.yaml
docker/docker-compose-dev.yaml
docker/docker-compose.yaml
wren-ai-service/demo/utils.py
wren-ai-service/poetry.lock
wren-ai-service/pyproject.toml
wren-ai-service/src/providers/document_store/qdrant.py
wren-ai-service/tools/dev/docker-compose-dev.yaml

- remove unused deps and reorganize pyproject.yaml
- upgrade haystack and qdrant-haystack
- upgrade qdrant to v1.11.0: https://qdrant.tech/blog/qdrant-1.11.x/

chore(wren-ai-service): update deps

---

wren-ai-service/eval/.env.example
wren-ai-service/eval/data_curation/utils.py
wren-ai-service/eval/evaluation.py
wren-ai-service/eval/metrics/column.py
wren-ai-service/eval/pipelines.py
wren-ai-service/eval/prediction.py
wren-ai-service/eval/utils.py
wren-ai-service/poetry.lock
wren-ai-service/pyproject.toml

- add some messages after running prediction and evaluation for better ux
- upgrade deepeval to 1.0.6
- some simple refactor
- fix accuracy metric

chore(wren-ai-service): fix eval

---

wren-ai-service/eval/preparation.py

handle cases where csv removes models and columns for mdl preparation

chore(wren-ai-service): improve eval data preparation

---

wren-ai-service/src/pipelines/ask/retrieval.py
wren-ai-service/src/pipelines/indexing/indexing.py
wren-ai-service/src/providers/document_store/qdrant.py

fix duplicated key `id` in document

chore(wren-ai-service): fix document meta

---

wren-ai-service/src/pipelines/ask/historical_question.py
wren-ai-service/src/pipelines/indexing/indexing.py
wren-ai-service/tests/pytest/pipelines/test_view_converter.py

- compare user's question to view's question
- adjust score to 0.9
- add descend sorting by score to ScoreFilter component

chore(wren-ai-service): fix view candidate indexing and retrieval

---

wren-ai-service/src/globals.py
wren-ai-service/src/pipelines/ask/historical_question.py
wren-ai-service/src/pipelines/ask/retrieval.py
wren-ai-service/src/pipelines/indexing/indexing.py
wren-ai-service/tests/pytest/pipelines/test_ask.py

- revert breaking change on qdrant collection name
- fix filter logic

chore(wren-ai-service): fix bugs

---

wren-ai-service/src/pipelines/indexing/indexing.py
wren-ai-service/src/web/v1/services/ask.py

- should include previous query summary in follow-up asking process
- add whitelist for model and column properties for indexing

chore(wren-ai-service): refine retrieval in follow-up question

---

wren-ai-service/eval/dashboard/analysis.ipynb
wren-ai-service/src/providers/embedder/openai.py
wren-ai-service/src/providers/llm/openai.py

- update langfuse data analysis notebook
- remove openai api key validation since it shows 404 often

chore(wren-ai-service): minor updates

---

wren-ai-service/src/pipelines/generation/sql_correction.py

fix no database schema in prompt issue

fix(wren-ai-service): no db schema in sql correction prompt

---

wren-ai-service/src/pipelines/common.py
wren-ai-service/src/pipelines/generation/followup_sql_generation.py
wren-ai-service/src/pipelines/generation/sql_generation.py
wren-ai-service/src/web/v1/services/ask.py
wren-ai-service/tests/pytest/services/mocks.py

add fiscal year configurations to ask/follow up ask

chore(wren-ai-service): update ask api

---

wren-ui/src/apollo/client/graphql/__types__.ts
wren-ui/src/apollo/server/data/sample.ts
wren-ui/src/apollo/server/data/type.ts
wren-ui/src/apollo/server/resolvers/projectResolver.ts
wren-ui/src/apollo/server/schema.ts
wren-ui/src/apollo/server/services/modelService.ts
wren-ui/src/apollo/server/types/relationship.ts
wren-ui/src/components/pages/setup/utils.tsx

change sample dataset to "E-commerce" & "HR".

Feature: change sample dataset

---

README.md

- remove blog posts in Readme
- Add contribution guidelines in Readme

Add contribution guideline section

---

deployment/kustomizations/README.md

docs: update kustomizations/README.md

---

deployment/kustomizations/kustomization.yaml

fix(deployment): add missing wren-ibis-server.yaml for kustomizations

---

wren-ui/src/apollo/server/mdl/mdlBuilder.ts

fix(wren-ui): mdl format of nested column

---

wren-ai-service/pyproject.toml

This reverts commit 16b1ee8295933e4d3ba6ff382b85cbd7c96bf3d1.

chore(wren-ai-service): revert "Upgrade AI Service version to 0.13.1"

---

README.md

- Follow Us: Change "Follow us" to "Follow us on X" for clarity.
- Hacktoberfest Link: Change "Holopin From Digital Ocean" to "Holopin from DigitalOcean" and add "a" before "Wren AI Exclusive Swag Pack."
- Wren UI Description: Remove "within Wren AI's framework" for conciseness.
- Code of Conduct: Change "Do note" to "Please note" for better flow.
- Self-Learning Feedback Loop: Change "semantics enhancement" to "semantic enhancements" for consistency.

Resolved Grammatical errors for better Flow and readability

---

wren-ui/src/apollo/server/adaptors/ibisAdaptor.ts
wren-ui/src/apollo/server/resolvers/modelResolver.ts

- inject description into properties when listing table from ibis server
- table
- column
- nestedColumn
BigQuery
- can import table & column & nested column's description from the data source

feature(wren-ui): inject description when import from ibis server

---

wren-ai-service/eval/prediction.py

- Fix connection info decode issue in eval prediction

chore(wren-ai-service): fix connection info decode issue in eval prediction

---

wren-ui/e2e/config.ts
wren-ui/e2e/specs/connectTrino.spec.ts

Fix: #704 
The tests mentioned in the issue have been added and tested locally

feat(wren-ui/e2e): Add E2E tests for Trino Data Source

---

wren-ui/src/components/pages/home/prompt/Result.tsx

This feature aims to show the candidate first while in the generating state.
Also, we provide skeletons to users to make it clear to know there is results will show after finishing the query.

feat(wren-ui): Add candidate showing flow when in generating state

---

wren-ui/e2e/config.ts
wren-ui/e2e/specs/connectClickHouse.spec.ts

Fixes #702 
The tests referenced in the issue have been implemented and verified locally with the results as shown below. Your review would be greatly appreciated, thanks in advance!

feat(wren-ui/e2e): Added E2E tests for ClickHouse Data Source

---

deployment/kustomizations/README.md

This PR updates the dead link in:
https://github.com/Canner/WrenAI/blob/c9706b52c455ea811b77fb80055ded76ef4144ad/deployment/kustomizations/README.md?plain=1#L101
Similar to #769.

docs: update dead link in `kustomizations/README.md`

---

wren-ui/src/apollo/server/adaptors/tests/ibisAdaptor.test.ts
wren-ui/src/hooks/useSetupConnection.tsx

fix(wren-ui): build

---

wren-ui/src/apollo/server/utils/error.ts

Rename `Ibis server error` to `Data connection error`

chore(wren-ui): rename to Data connection error

---

.github/workflows/ui-release-image-stable.yaml

fix the file directory in the Github action steps

chore(wren-ui): fix the file directory in the Github action steps

---

wren-ui/src/components/learning/guide/index.tsx
wren-ui/src/components/learning/guide/stories.tsx
wren-ui/src/components/learning/guide/utils.ts
wren-ui/src/components/learning/index.tsx
wren-ui/src/pages/modeling.tsx
wren-ui/src/styles/components/driver.less
wren-ui/src/utils/events.tsx
wren-ui/src/utils/icons.ts

This PR aims to help users quickly learn what they can do when asking questions.
- Improve the modeling popover position (set up block height initially) to prevent image on-load affect the popover position)
- Sync focus first model function when modeling guide start
https://github.com/user-attachments/assets/32004290-f6bc-4b8a-92fb-b9fb9254cfa6

feat(wren-ui): Implement home page onboarding guide

---

wren-ui/src/apollo/server/adaptors/ibisAdaptor.ts
wren-ui/src/apollo/server/adaptors/tests/ibisAdaptor.test.ts
wren-ui/src/apollo/server/services/queryService.ts
wren-ui/src/apollo/server/services/tests/queryService.test.ts

chore(wren-ui): fix lint

---

wren-ui/package.json

chore(wren-ui): revert wren-ui version

---

wren-ai-service/src/__main__.py
wren-ai-service/src/providers/__init__.py

chore(wren-ai-service): fix force deployment issue

---

README.md

add roadmap to readme

---

wren-ai-service/src/pipelines/common.py
wren-ai-service/src/pipelines/retrieval/retrieval.py

- Update retrieval prompt rule for GA4 struct type column

chore(wren-ai-service): Update retrieval prompt rule for GA4 struct type column

---

wren-ai-service/src/web/v1/routers/ask.py
wren-ai-service/src/web/v1/services/ask.py
wren-ai-service/tests/pytest/services/test_ask.py

chore(wren-ai-service): revert skip sql summary and add correcting status

---

wren-ai-service/src/pipelines/generation/semantics_description.py
wren-ai-service/src/web/v1/routers/semantics_description.py
wren-ai-service/src/web/v1/services/semantics_description.py

This PR introduces language configuration support in the semantics description pipeline, allowing users to generate model/column descriptions in different languages. The default language remains "English" if not specified.
- Added language configuration support in the semantics description pipeline
- Updated API contract to include optional language configuration
- Modified prompt template to include language parameter
- Default language is set to "English" if not specified
- Endpoint: `POST /v1/semantics-descriptions`
- Request Body
```json
{
"selected_models": [
"Student",
"Minor_in",
"Member_of",
"Gradeconversion",
"Faculty",
"Enrolled_in",
"Department",
"Course"
],
"user_prompt": "學生資料",
"mdl": "{\"catalog\":\"canner-cml\",\"schema\":\"spider\",\"models\":[{\"name\":\"Course\",\"proper …
```

feat(wren-ai-service): Language Support for Semantics Description Generation

---

wren-ui/src/apollo/client/graphql/__types__.ts
wren-ui/src/apollo/client/graphql/home.generated.ts
wren-ui/src/apollo/client/graphql/home.ts
wren-ui/src/components/pages/home/prompt/Result.tsx

fix(wren-ui): prompt result add wrapper after rebasing

---

wren-ui/src/pages/home/[id].tsx
wren-ui/src/pages/home/index.tsx

Add await for generateThreadRecommendationQuestions API

fix(wren-ui): await thread recommendation question generation

---

wren-ui/src/apollo/server/services/projectService.ts

fix generating RQ with incorrect language after updating project language

fix(wren-ui): fix generating RQ with incorrect language 

---

wren-ui/src/apollo/server/services/askingService.ts

chore(wren-ui): add comment

---

wren-ai-service/src/pipelines/generation/relationship_recommendation.py

This PR modifies the prompt template to explicitly handle localization for relationship names and reasons in the recommendation pipeline.

chore(wren-ai-service): enhance prompt for localization language

---

wren-ai-service/src/web/v1/services/question_recommendation.py

This PR fixes an issue around handling question validation and category limits.
- Added proper return values for validation steps for tracing
- Improved category and question limit handling

fix(wren-ai-service): wrong condition to avoid lacking some valid question

---

wren-ui/src/components/pages/home/RecommendedQuestions.tsx
wren-ui/src/components/pages/home/prompt/DemoPrompt.tsx
wren-ui/src/components/pages/home/prompt/RecommendedQuestionsPrompt.tsx
wren-ui/src/components/pages/home/prompt/index.tsx
wren-ui/src/components/pages/home/promptThread/AnswerResult.tsx
wren-ui/src/components/pages/home/promptThread/index.tsx
wren-ui/src/hooks/useRecommendedQuestionsInstruction.tsx
wren-ui/src/pages/home/[id].tsx
wren-ui/src/pages/home/index.tsx

- Recommendation questions enhancement
- Click recommended questions to go to thread creation
- still show recommend questions if generated answer result failed

feat(wren-ui): Click recommended questions to go to thread creation

---

wren-ui/src/components/pages/home/prompt/RecommendedQuestionsPrompt.tsx

- add text truncate to recommend questions label
- add HTML title to label

chore(wren-ui): Add text-truncate to recommend questions label

---

wren-ui/src/pages/modeling.tsx

- Add loading state for edit metadata updates
- Add & improve others submission status

chore(wren-ui): Add loading state for edit metadata updates

---

wren-ui/src/components/pages/home/prompt/RecommendedQuestionsPrompt.tsx
wren-ui/src/pages/home/index.tsx
wren-ui/src/styles/utilities/display.less

- add loading indicators for recommended question selection
https://github.com/user-attachments/assets/a5f3288d-968e-4ed0-8ab1-4a9b5202b93a

chore(wren-ui): add loading indicators for recommended question selection

---

wren-ai-service/poetry.lock
wren-ai-service/pyproject.toml
wren-ai-service/src/core/provider.py
wren-ai-service/src/pipelines/generation/data_assistance.py
wren-ai-service/src/pipelines/generation/followup_sql_generation.py
wren-ai-service/src/pipelines/generation/intent_classification.py
wren-ai-service/src/pipelines/generation/question_recommendation.py
wren-ai-service/src/pipelines/generation/relationship_recommendation.py
wren-ai-service/src/pipelines/generation/semantics_description.py
wren-ai-service/src/pipelines/generation/sql_breakdown.py
wren-ai-service/src/pipelines/generation/sql_correction.py
wren-ai-service/src/pipelines/generation/sql_expansion.py
wren-ai-service/src/pipelines/generation/sql_explanation.py
wren-ai-service/src/pipelines/generation/sql_generation.py
wren-ai-service/src/pipelines/generation/sql_regeneration.py
wren-ai-service/src/pipelines/generation/sql_summary.py
wren-ai-service/src/pipelines/retrieval/retrieval.py
wren-ai-service/src/providers/__init__.py
wren-ai-service/src/providers/llm/__init__.py
wren-ai-service/src/providers/llm/azure_openai.py
wren-ai-service/src/providers/llm/litellm.py
wren-ai-service/src/providers/llm/lm.py
wren-ai-service/src/providers/llm/ollama.py
wren-ai-service/src/providers/llm/openai.py
wren-ai-service/tests/pytest/providers/test_loader.py
wren-ai-service/tools/config/config.full.yaml

- tested using OpenAI and Ollama
- for setup, could check tools/config/config.full.yaml
- in the future, users only need to update config and environment variable for api keys to use new llms
- this PR only implements LLM. we could implement embedder in the future

feat(wren-ai-service): litellm integration

---

.github/workflows/ai-service-release-stable-image.yaml

- Added error handling to the change log generation command using `|| true`
- Prevents workflow failure when no matching commits are found between versions
- Affects the stable image release workflow for AI service

chore(wren-ai-service): fix changelog generation in ai service release workflow

---

wren-ai-service/src/core/engine.py
wren-ai-service/src/providers/llm/azure_openai.py
wren-ai-service/src/providers/llm/litellm.py
wren-ai-service/src/providers/llm/ollama.py
wren-ai-service/src/providers/llm/openai.py

- remove redundant variable: `chunk`
- fix azure_openai and litllm streaming callback issue
- stabilize json output

chore(wren-ai-service): fix llm issues

---

wren-ai-service/src/pipelines/generation/data_assistance.py
wren-ai-service/src/pipelines/generation/intent_classification.py

- there should be no sql in GENERAL streaming response
- we should not accept sql in user input
- follow-up ask improvement

chore(wren-ai-service): refine ai service

---

.github/workflows/ai-service-test.yaml
wren-ai-service/src/web/v1/routers/semantics_preparations.py
wren-ai-service/tests/pytest/pipelines/test_ask.py
wren-ai-service/tests/pytest/pipelines/test_ask_details.py
wren-ai-service/tests/pytest/services/test_ask.py
wren-ai-service/tests/pytest/services/test_ask_details.py
wren-ai-service/tests/pytest/test_config.py

1. **Test Infrastructure**
- Replaced direct provider initialization with `generate_components`
- Simplified test fixtures using component-based DI
- Removed redundant provider initialization code
2. **CI/CD Improvements**
- Simplified GitHub Actions configuration
- Moved environment variables to `just init --non-dev`
3. **API Enhancement**
- Made `project_id` required in `/semantics` DELETE endpoint
- Added proper validation with HTTP 400 error

chore(wren-ai-service): component-based architecture refactoring for test cases and required project id for semantics deletion

---

.github/ISSUE_TEMPLATE/bug_report.md

chore: add log for bug report

---

wren-ui/src/apollo/server/resolvers/modelResolver.ts
wren-ui/src/apollo/server/resolvers/projectResolver.ts
wren-ui/src/pages/modeling.tsx

- trigger polling initially
- prevent generate recommend questions when deploying if using sample dataset

fix(wren-ui): trigger polling initially & prevent generate recommend questions when deploying if using sample dataset

---

wren-ui/e2e/commonTests/home.ts
wren-ui/e2e/commonTests/modeling.ts
wren-ui/e2e/config.ts
wren-ui/e2e/helper.ts
wren-ui/e2e/specs/connectSampleECommerce.spec.ts
wren-ui/e2e/specs/connectSampleHR.spec.ts
wren-ui/migrations/20241207000000_update_thread_response_for_answer.js
wren-ui/src/components/pages/home/prompt/Result.tsx

Fix broken E2E tests caused by recent changes to features and enhancement tasks.

feat(e2e): fix E2E broken tests

---

wren-ui/src/components/pages/home/promptThread/TextBasedAnswer.tsx

chore(wren-ui): add alert info to users if no rows

---

wren-ui/src/components/pages/home/promptThread/TextBasedAnswer.tsx

Fix alert info to show when streaming finishes

fix(wren-ui): alert info to show when streaming finishes

---

wren-ui/src/components/chart/handler.ts

Fix the chart sortBy logic to descent to show the top 25 values

fix(wren-ui): chart sortBy categories to descent

---

wren-ui/src/apollo/server/resolvers/askingResolver.ts

fix(wren-ui): fix breakdown sql

---

docker/.env.example
docker/docker-compose-dev.yaml

chore: fix docker configs

---

wren-ui/src/apollo/server/backgrounds/textBasedAnswerBackgroundTracker.ts
wren-ui/src/apollo/server/resolvers/askingResolver.ts
wren-ui/src/apollo/server/services/askingService.ts
wren-ui/src/apollo/server/services/projectService.ts

- fix answerDetail nested resolver (for considering old data situation)
- fix invalid language issue

fix(wren-ui): fix answerDetail nested resolver for text-to-answer

---

wren-ai-service/src/utils.py

use Exception instead of ImportError

chore(wren-ai-service): minor update

---

deployment/kustomizations/base/cm.yaml
docker/config.example.yaml
wren-ai-service/src/globals.py
wren-ai-service/tools/config/config.example.yaml
wren-ai-service/tools/config/config.full.yaml

- Added new dedicated pipeline configurations for question recommendation components:
- `question_recommendation_db_schema_retrieval`: Handles database schema retrieval with embedding support
- `question_recommendation_sql_generation`: Manages SQL query generation for recommended questions

chore(wren-ai-service): Add Dedicated Pipes for Question Recommendation Components

---

wren-ui/src/apollo/server/utils/model.ts

use ref name to build sql statement

fix(wren-ui): use ref name to build sql statement 

---

wren-ai-service/eval/pipelines.py
wren-ai-service/eval/prediction.py
wren-ai-service/src/core/engine.py
wren-ai-service/src/pipelines/common.py
wren-ai-service/src/pipelines/generation/followup_sql_generation.py
wren-ai-service/src/pipelines/generation/intent_classification.py
wren-ai-service/src/pipelines/generation/sql_correction.py
wren-ai-service/src/pipelines/generation/sql_generation.py
wren-ai-service/src/pipelines/generation/utils/sql.py
wren-ai-service/src/pipelines/retrieval/retrieval.py
wren-ai-service/src/web/v1/services/ask.py
wren-ai-service/src/web/v1/services/question_recommendation.py
wren-ai-service/tests/pytest/pipelines/generation/test_ask.py

- fix eval indexing
- improve text2sql using reasoning

chore(wren-ai-service): improve text2sql

---

wren-ui/src/apollo/server/data/sample.ts

Fix(wren-ui): change sample question

---

wren-ui/src/components/pages/home/preparation/step/Retrieving.tsx

fix(wren-ui): add margin to tag in retrieving

---

.github/workflows/ui-release-image-stable.yaml

chore(workflow): fix latest tag

---

wren-ui/src/components/chart/handler.ts

add optional chaining to prevent null in chart schema

fix(wren-ui): optional chaining to prevent null in chart schema

---

wren-ui/src/components/modals/AdjustReasoningStepsModal.tsx
wren-ui/src/utils/error/dictionary.ts

extend reasoning text limit to 6000

chore(wren-ui): extend reasoning text limit to 6000
